/* ATHANOR — IL VIAGGIO SI ALLARGA. Il fiume, il borgo di pietra, l'uliveto e
   la vigna, il porto e la spiaggia d'inverno, i fuochi fatui nel cimitero e le
   voci della notte, le cose misteriose, le cose tristi che succedono a tutti,
   i pensieri di rinascita, e il nulla: camminare dove non c'è niente.
   Le strade tra i luoghi le disegna loca-layout.js.
   un luogo moderatamente sicuro */
window.ATH = window.ATH || {};

(function (ATH) {
  const N = (id, name, kind, level, o) => Object.assign({ id, name, kind, level, exits: [], motif: {} }, o);
  const NEW = [
    // ——————————————————————— IL MARE
    N('porto', 'Il porto di notte', 'luogo', 0, { terrain: 'legno', modus: 'eolio', hush: 0.45, lumina: 'soffuse',
      levels: { m_mare: 0.35, m_scricchiolio: 0.3, m_gabbiani: 0.08, m_campane: 0.08, m_vento: 0.25, m_radio: 0.06 }, set: { lumen: 0.3, crypta: 0.6, distantia: 0.5 }, libra: 0.7,
      pal: { bg: [6, 8, 11], accent: [214, 200, 160], second: [70, 100, 130] }, motif: { lights: 0.6, lake: 0.3 },
      ora: 'Le barche legate che si strusciano contro il molo, le cime che cigolano, una lampada gialla sopra la porta della capitaneria. L’acqua schiaffeggia piano lo scafo.',
      allora: 'Venivi a guardare i pescherecci che rientravano all’alba. Gli uomini non parlavano: erano troppo stanchi, o troppo felici di essere tornati.' }),
    N('molo', 'In fondo al molo', 'luogo', 0, { terrain: 'pietra', modus: 'pentatonico', hush: 0.6, peace: 70, lumina: 'soffuse',
      levels: { m_mare: 0.5, m_vento: 0.35, m_gabbiani: 0.1 }, set: { lumen: 0.35, aether: 0.6, crypta: 0.8 }, libra: 0.8,
      pal: { bg: [7, 9, 12], accent: [200, 214, 230], second: [80, 110, 140] }, motif: { lake: 0.6, beam: 0.3 },
      ora: 'In fondo al molo, dove finiscono i lampioni. Ti siedi sui massi, con le gambe a penzoloni sull’acqua. Davanti non c’è più niente da guardare, solo da ascoltare.',
      allora: 'Qui venivi quando non sapevi più dove andare. Il mare non risolveva niente, ma metteva tutto alla giusta distanza.' }),
    N('spiaggia_inverno', 'La spiaggia d’inverno', 'luogo', 0, { terrain: 'sabbia', modus: 'eolio', hush: 0.5, lumina: 'soffuse',
      levels: { m_mare: 0.6, m_vento: 0.55, m_gabbiani: 0.15 }, set: { lumen: 0.3, crypta: 0.75, distantia: 0.5 }, libra: 0.7,
      pal: { bg: [10, 11, 12], accent: [210, 214, 216], second: [110, 120, 128] }, motif: { haze: 0.6, ruin: 0.3, path: 0.4 },
      ora: 'Gli ombrelloni chiusi e legati, le cabine con le assi sbiadite, la sabbia bagnata e piena di legni portati dal mare. Un cane corre da solo lungo la riva.',
      allora: 'D’estate era piena di voci. Adesso sembra un posto dove l’estate è morta e nessuno se n’è accorto. Ma è più vera così.' }),
    // ——————————————————————— LA CAMPAGNA
    N('grano', 'Il campo di grano di notte', 'luogo', 0, { terrain: 'erba', modus: 'lidio', hush: 0.5, lumina: 'soffuse',
      levels: { m_grilli: 0.55, m_vento: 0.35, m_foglie: 0.2, m_civetta: 0.08, m_cani: 0.06 }, set: { lumen: 0.35, aether: 0.5 }, libra: 0.75,
      pal: { bg: [9, 8, 6], accent: [236, 210, 150], second: [130, 110, 70] }, motif: { field: 1, stars: 0.6, fireflies: 0.3 },
      ora: 'Il grano alto fino alla vita, che si piega tutto insieme quando passa il vento, come un mare. Migliaia di grilli. Sopra, una luna che sembra di carta.',
      allora: 'Ci correvi dentro da bambino, e il contadino ti sgridava da lontano. Le spighe ti graffiavano le braccia, e non te ne importava niente.' }),
    N('vigna', 'La vigna', 'luogo', 0, { terrain: 'erba', modus: 'ionio', hush: 0.45, lumina: 'accese',
      levels: { m_cicale: 0.4, m_uccelli: 0.25, m_vento: 0.2, m_voci: 0.12, m_campane: 0.08 }, set: { lumen: 0.35, velum: 0.4 }, libra: 0.7,
      pal: { bg: [14, 11, 9], accent: [226, 180, 120], second: [120, 70, 90] }, motif: { field: 0.5, haze: 0.6, sun: 0.3 },
      ora: 'I filari in collina, le foglie che diventano rosse, le cassette di legno sotto le viti. Da lontano qualcuno canta mentre vendemmia.',
      allora: 'Il nonno ti dava un grappolo da mangiare, ancora caldo di sole. Le mani appiccicose per tutto il pomeriggio.' }),
    N('uliveto', 'L’uliveto', 'luogo', 0, { terrain: 'erba', modus: 'dorico', hush: 0.65, peace: 80, lumina: 'accese',
      levels: { m_cicale: 0.3, m_vento: 0.3, m_uccelli: 0.2, m_foglie: 0.3, m_campanacci: 0.05 }, set: { lumen: 0.4, velum: 0.45, aether: 0.4 }, libra: 0.82,
      pal: { bg: [11, 12, 10], accent: [210, 220, 190], second: [120, 140, 110] }, motif: { trees: 0.5, haze: 0.5, sun: 0.25 },
      ora: 'Gli ulivi vecchi, contorti, con il tronco aperto come una mano. Le foglie d’argento girano col vento. Sotto, l’erba alta e le reti arrotolate per la raccolta.',
      allora: 'Hanno visto passare le guerre, le carestie, i tuoi nonni da giovani. Saranno qui anche dopo di te. È un pensiero che consola.' }),
    N('treno_merci', 'Il treno merci', 'luogo', 0, { terrain: 'ghiaia', modus: 'hirajoshi', hush: 0.3, lumina: 'spente',
      levels: { m_treno: 0.6, m_grilli: 0.3, m_vento: 0.2, m_cani: 0.08 }, set: { lumen: 0.2, distantia: 0.7, crypta: 0.7 }, libra: 0.6,
      pal: { bg: [7, 7, 8], accent: [200, 196, 190], second: [100, 96, 100] }, motif: { train: 0.8, path: 0.4 },
      ora: 'Di notte, in mezzo ai campi, passa un treno merci lunghissimo. Vagoni chiusi, uno dopo l’altro, che non finiscono mai. Poi il silenzio, e i grilli che ricominciano.',
      allora: 'Contavi i vagoni dal letto, con la finestra aperta d’estate. Non sei mai arrivato alla fine: ti addormentavi prima.' }),
    // ——————————————————————— IL FIUME
    N('ruscello', 'Il ruscello', 'luogo', 0, { terrain: 'acqua', modus: 'pentatonico', hush: 0.55, lumina: 'accese',
      levels: { m_ruscello: 0.6, m_uccelli: 0.3, m_foglie: 0.25, m_rane: 0.08 }, set: { lumen: 0.35, velum: 0.4, aether: 0.4 }, libra: 0.78,
      pal: { bg: [8, 11, 10], accent: [190, 226, 210], second: [80, 130, 120] }, motif: { river: 0.6, trees: 0.4, motes: 0.4 },
      ora: 'L’acqua corre veloce tra i sassi lisci, fa piccoli salti, si ferma in pozze chiare dove si vedono i girini. Ha sempre qualcosa da dire.',
      allora: 'Ci costruivi le dighe con i sassi, e l’acqua le smontava ogni volta. Non ti arrendevi. Era il tuo primo lavoro da ingegnere.' }),
    N('ponte', 'Il ponte di legno', 'luogo', 0, { terrain: 'legno', modus: 'dorico', hush: 0.45, lumina: 'soffuse',
      levels: { m_ruscello: 0.45, m_scricchiolio: 0.3, m_vento: 0.2, m_passi: 0.15 }, set: { lumen: 0.3, distantia: 0.4 }, libra: 0.7,
      pal: { bg: [9, 9, 8], accent: [210, 190, 160], second: [100, 110, 100] }, motif: { river: 0.5, path: 0.3 },
      ora: 'Un ponte di assi sul fiume, con il corrimano consumato dalle mani. Ogni passo scricchiola. Sotto, l’acqua scura che non si ferma.',
      allora: 'Buttavi un rametto da una parte e correvi dall’altra a vederlo uscire. A volte non usciva più. Ti sembrava una cosa molto seria.' }),
    N('mulino', 'Il mulino abbandonato', 'luogo', 0, { terrain: 'legno', modus: 'insen', hush: 0.5, lumina: 'soffuse',
      levels: { m_ruscello: 0.4, m_scricchiolio: 0.4, m_vento: 0.3, m_goccia: 0.2, m_uccelli: 0.06 }, set: { lumen: 0.25, crypta: 0.7, oblio: 0.4 }, libra: 0.7,
      pal: { bg: [9, 8, 7], accent: [214, 190, 150], second: [100, 90, 70] }, motif: { machine: 0.4, ruin: 0.7, motes: 0.5 },
      ora: 'La ruota di legno è ferma, coperta di muschio. L’acqua le passa accanto senza più spingerla. Dentro, le macine immobili e la farina diventata polvere grigia.',
      allora: 'Girava giorno e notte, una volta. Chi ci viveva si addormentava con quel rumore e si svegliava se smetteva.' }),
    N('cascata', 'La cascata', 'luogo', 0, { terrain: 'acqua', modus: 'armonici', hush: 0.2, lumina: 'soffuse',
      levels: { m_ruscello: 0.7, m_mare: 0.2, m_vento: 0.25, m_goccia: 0.2 }, set: { lumen: 0.35, aether: 0.7, crypta: 0.85 }, libra: 0.6,
      pal: { bg: [7, 10, 11], accent: [210, 236, 240], second: [90, 140, 150] }, motif: { river: 0.8, haze: 0.7, glass: 0.3 },
      ora: 'L’acqua cade da un salto di roccia e ruggisce in una pozza profonda. La nebbiolina ti bagna la faccia. Il rumore è così forte che dentro si può pensare in pace.',
      allora: 'Dicono che dietro il velo d’acqua ci sia una grotta. Bisogna avere il coraggio di passarci attraverso.' }),
    N('canneto', 'Il canneto', 'luogo', 0, { terrain: 'acqua', modus: 'hirajoshi', hush: 0.5, lumina: 'soffuse',
      levels: { m_rane: 0.45, m_foglie: 0.35, m_vento: 0.3, m_uccelli: 0.12, m_ronzio: 0.1 }, set: { lumen: 0.3, distantia: 0.5 }, libra: 0.72,
      pal: { bg: [8, 9, 7], accent: [200, 206, 150], second: [100, 110, 70] }, motif: { trees: 0.3, fog: 0.3, fireflies: 0.3 },
      ora: 'Le canne più alte di te, che si toccano e frusciano tutte insieme. Dentro c’è un sentiero stretto, battuto da qualcuno. Le rane tacciono quando passi.',
      allora: 'Ci giocavi a nascondino, e una volta nessuno ti ha trovato. Sei rimasto lì fino a sera, contento e un po’ triste.' }),
    N('lago_ghiacciato', 'Il lago ghiacciato', 'luogo', 0, { terrain: 'neve', modus: 'armonici', hush: 0.7, peace: 80, lumina: 'soffuse',
      levels: { m_ghiaccio: 0.55, m_vento: 0.35, m_campane: 0.05 }, set: { lumen: 0.35, aether: 0.8, crypta: 0.95 }, libra: 0.85,
      pal: { bg: [9, 11, 14], accent: [220, 236, 250], second: [120, 150, 190] }, motif: { ice: 1, snow: 0.4 },
      ora: 'Il lago è diventato una lastra bianca. Ogni tanto il ghiaccio canta: un suono lungo, come una corda tirata che corre da una riva all’altra, sotto i piedi.',
      allora: 'Nessuno ci cammina sopra, e nessuno sa davvero quanto sia spesso. Si guarda dalla riva, e si ascolta.' }),
    N('porta_bosco', 'La porta nel bosco', 'luogo', 0, { terrain: 'foglie', modus: 'hirajoshi', hush: 0.75, lumina: 'spente',
      levels: { m_foglie: 0.35, m_civetta: 0.2, m_vento: 0.25, m_carillon: 0.06, m_sussurri: 0.08 }, set: { lumen: 0.25, distantia: 0.7, mercurius: 0.5 }, libra: 0.8,
      pal: { bg: [4, 6, 5], accent: [240, 214, 160], second: [70, 90, 70] }, motif: { door: 1, trees: 0.6 },
      clues: ['In mezzo agli alberi c’è una porta.', 'Solo la porta, con il suo stipite. Nessun muro intorno.', 'Ci giri attorno: dall’altra parte è solo bosco.', 'Sotto la porta, però, filtra una luce calda.', 'E da dietro, piano, qualcuno carica un carillon.'],
      ora: 'Una porta di legno verniciato di verde, in piedi da sola tra i tronchi, chiusa. Dalla fessura in basso esce una lama di luce gialla.',
      allora: '' }),
    // ——————————————————————— IL BORGO
    N('borgo', 'Il borgo di pietra', 'luogo', 0, { terrain: 'pietra', modus: 'dorico', hush: 0.45, lumina: 'soffuse',
      levels: { m_campane: 0.25, m_passi: 0.25, m_vento: 0.25, m_voci: 0.12, m_cani: 0.08, m_rondini: 0 }, set: { lumen: 0.3, crypta: 0.7 }, libra: 0.68,
      pal: { bg: [10, 9, 8], accent: [222, 200, 170], second: [120, 100, 84] }, motif: { windows: 0.5, city: 0.3 },
      ora: 'Un paese di pietra in cima alla collina, chiuso dentro le mura. Vicoli che salgono a scale, archi, gatti sui gradini. Le campane battono le ore per pochi.',
      allora: 'Da qui si vede tutta la valle. Di notte le luci dei paesi intorno sembrano un’altra costellazione, caduta più in basso.' }),
    N('mura', 'Sulle mura antiche', 'luogo', 0, { terrain: 'pietra', modus: 'eolio', hush: 0.55, lumina: 'soffuse',
      levels: { m_vento: 0.5, m_campane: 0.15, m_uccelli: 0.15, m_cani: 0.06 }, set: { lumen: 0.35, aether: 0.6, crypta: 0.85 }, libra: 0.75,
      pal: { bg: [9, 9, 10], accent: [214, 206, 190], second: [100, 104, 116] }, motif: { haze: 0.5, mountain: 0.4 },
      ora: 'Le mura enormi, fatte di blocchi che nessuno saprebbe più sollevare. Ci cammini sopra al tramonto, e la valle sotto diventa azzurra.',
      allora: 'Le hanno costruite per difendersi da qualcosa che non c’è più. Restano, e adesso difendono solo il silenzio.' }),
    N('fontana', 'La fontana della piazza', 'luogo', 0, { terrain: 'pietra', modus: 'ionio', hush: 0.5, lumina: 'soffuse',
      levels: { m_goccia: 0.4, m_ruscello: 0.2, m_passi: 0.15, m_voci: 0.1, m_campane: 0.1 }, set: { lumen: 0.3, crypta: 0.7 }, libra: 0.72,
      pal: { bg: [9, 10, 10], accent: [200, 214, 214], second: [100, 116, 120] }, motif: { glass: 0.3, windows: 0.4 },
      ora: 'La piazza vuota di notte, i lampioni accesi, e la fontana che continua a parlare da sola. Sul fondo, monete verdi di chi ha espresso un desiderio.',
      allora: 'Hai buttato una moneta anche tu, una volta. Non ricordi più cosa avevi chiesto. Forse si è avverato, e non te ne sei accorto.' }),
    N('orologio_fermo', 'La torre dell’orologio fermo', 'luogo', 0, { terrain: 'scala', modus: 'insen', hush: 0.8, lumina: 'torcia',
      levels: { m_vento: 0.3, m_scricchiolio: 0.3, m_pendolo: 0.0, m_goccia: 0.15, m_uccelli: 0.06 }, set: { lumen: 0.2, oblio: 0.5, distantia: 0.6 }, libra: 0.8,
      pal: { bg: [8, 8, 9], accent: [214, 200, 170], second: [100, 96, 90] }, motif: { machine: 0.6, motes: 0.7, door: 0.3 },
      clues: ['Le lancette segnano le tre e un quarto.', 'Da quanti anni? Nessuno lo ricorda.', 'Gli ingranaggi sono puliti, come se qualcuno li curasse.', 'Sul pavimento, impronte nella polvere. Recenti.', 'Ogni tanto, la notte, si sente un solo rintocco.'],
      ora: 'Una scala di legno sale dentro la torre, fino agli ingranaggi. Tutto è fermo. Eppure qui dentro il tempo sembra trattenere il fiato.',
      allora: '' }),
    N('campana_sola', 'La campana che suona da sola', 'luogo', 0, { terrain: 'pietra', modus: 'eolio', hush: 0.7, lumina: 'spente',
      levels: { m_campane: 0.35, m_vento: 0.4, m_civetta: 0.12, m_richiamo: 0.1 }, set: { lumen: 0.25, crypta: 0.95, distantia: 0.7 }, libra: 0.8,
      pal: { bg: [6, 6, 8], accent: [200, 196, 214], second: [90, 90, 120] }, motif: { candles: 0.2, haze: 0.4, wisps: 0.3 },
      ora: 'Una chiesetta di campagna, chiusa da anni, senza corda nel campanile. Eppure certe notti la campana suona, un colpo solo, e il suono va lontano.',
      allora: 'Dicono che suoni quando qualcuno, da qualche parte, se ne va senza che nessuno lo sappia. Così almeno lei lo saluta.' }),
    N('casa_luce', 'La casa con la luce accesa', 'luogo', 0, { terrain: 'ghiaia', modus: 'lidio', hush: 0.75, lumina: 'spente',
      levels: { m_grilli: 0.35, m_vento: 0.2, m_grammofono: 0.08, m_cani: 0.06 }, set: { lumen: 0.3, distantia: 0.75, oblio: 0.5 }, libra: 0.8,
      pal: { bg: [5, 5, 6], accent: [250, 210, 140], second: [100, 80, 60] }, motif: { door: 1, windows: 0.3 },
      clues: ['Una casa sola in fondo alla strada bianca.', 'Una finestra è sempre accesa, giorno e notte.', 'Nessuno entra, nessuno esce.', 'Ti avvicini e senti, piano, una musica di grammofono.', 'Quando bussi, la musica si ferma.'],
      ora: 'Tutto intorno è buio, campi e alberi. Solo una finestra, gialla e calda, come se qualcuno ti stesse aspettando da sempre.',
      allora: '' }),
    // ——————————————————————— LA CASA DEI NONNI
    N('casa_venduta', 'La casa venduta', 'stato', 0, { terrain: 'legno', modus: 'eolio', hush: 0.85, lumina: 'soffuse',
      levels: { m_passi: 0.15, m_vento: 0.2, m_scricchiolio: 0.25, m_motore: 0.08 }, set: { lumen: 0.25, oblio: 0.5, distantia: 0.6 }, libra: 0.82,
      pal: { bg: [10, 9, 9], accent: [210, 196, 180], second: [110, 100, 96] }, motif: { ruin: 0.3, motes: 0.6, wallpaper: 0.3 },
      clues: ['Le stanze vuote, i segni chiari dove c’erano i quadri.', 'Il chiodo dove stava il calendario.', 'Il segno sullo stipite con le tue altezze, anno dopo anno.', 'Domani ci verranno a vivere altri.', 'Chiudi la porta. Le chiavi le lasci sul tavolo.'],
      ora: 'La casa dei nonni, venduta. I mobili portati via, le voci rimbombano. Il pavimento ha ancora la forma dei loro passi, ma presto non sarà più così.',
      allora: '' }),
    // ——————————————————————— LA NOTTE
    N('insonnia', 'Le tre di notte', 'stato', 0, { terrain: 'legno', modus: 'hirajoshi', hush: 0.8, lumina: 'spente',
      levels: { m_pendolo: 0.35, m_ronzio: 0.2, m_tubature: 0.12, m_cuore: 0.2, m_motore: 0.06, m_acufene: 0.12 }, set: { lumen: 0.2, nastro: 0.3, distantia: 0.4 }, libra: 0.8, bpm: 0.5,
      pal: { bg: [5, 6, 8], accent: [190, 200, 220], second: [80, 90, 110] }, motif: { ceiling: 0.8, monitor: 0.15 },
      clues: ['Sono le tre e ventidue.', 'Hai girato il cuscino dal lato fresco.', 'Ripassi una conversazione di dieci anni fa.', 'Il frigorifero si accende, poi si spegne.', 'Mancano quattro ore alla sveglia. Poi tre e cinquanta.', 'Un’auto passa, e la luce dei fari scorre sul soffitto.'],
      ora: 'Il soffitto, al buio. Tutti dormono, tranne te e i pensieri. Le cose piccole diventano enormi, a quest’ora.',
      allora: '' }),
    // ——————————————————————— LE VOCI DELLA NOTTE
    N('voci_notte', 'Le voci della notte', 'luogo', 0, { terrain: 'pietra', modus: 'insen', hush: 0.6, lumina: 'spente',
      levels: { m_richiamo: 0.45, m_voci: 0.2, m_sussurri: 0.2, m_cani: 0.15, m_grilli: 0.3, m_civetta: 0.15 }, set: { lumen: 0.2, distantia: 0.8, crypta: 0.85 }, libra: 0.75,
      pal: { bg: [5, 6, 8], accent: [190, 196, 220], second: [70, 80, 110] }, motif: { whispers: 0.6, windows: 0.3 },
      ora: 'Di notte, con la finestra aperta, arrivano voci da lontano: qualcuno che chiama un nome, una lite smorzata, una risata, un cane che risponde a un altro cane. Non si capisce mai da dove.',
      allora: 'Da bambino pensavi che fossero le voci dei sogni degli altri, scappate dalle case mentre dormivano.' }),
    N('radio_notte', 'La radio di notte', 'luogo', 0, { terrain: 'legno', modus: 'dorico', hush: 0.7, lumina: 'soffuse',
      levels: { m_radio: 0.55, m_fruscio: 0.3, m_pendolo: 0.15, m_pioggia: 0.15 }, set: { lumen: 0.25, nastro: 0.6, distantia: 0.5 }, libra: 0.8,
      pal: { bg: [8, 7, 6], accent: [240, 190, 110], second: [120, 80, 50] }, motif: { lights: 0.3, motes: 0.4 },
      ora: 'La radiolina sul comodino, la lucina arancione della scala. Giri la manopola: una voce in una lingua che non conosci, una canzone vecchia, poi solo fruscio, come il mare.',
      allora: 'Ci dormivi accanto, con il volume al minimo. Ti bastava sapere che da qualche parte qualcuno era sveglio e parlava.' }),
    N('lettera_mai', 'La lettera mai spedita', 'stato', 0, { terrain: 'legno', modus: 'eolio', hush: 0.85, lumina: 'candele',
      levels: { m_fruscio: 0.35, m_pendolo: 0.25, m_candele: 0.2, m_pioggia: 0.12 }, set: { lumen: 0.3, oblio: 0.35 }, libra: 0.85,
      pal: { bg: [10, 9, 8], accent: [230, 210, 176], second: [120, 100, 80] }, motif: { candles: 0.5, motes: 0.5 },
      clues: ['Caro…', 'Volevo dirti che mi dispiace.', 'Volevo dirti che avevi ragione tu.', 'Volevo dirti grazie, e non l’ho mai fatto.', 'La busta è ancora nel cassetto, con il francobollo vecchio.', 'Adesso non c’è più un indirizzo a cui mandarla.'],
      ora: 'Un foglio piegato in quattro, la calligrafia tua di tanti anni fa. Lo hai scritto di notte, lo hai riletto la mattina, e lo hai messo via.',
      allora: '' }),
    N('ultima_telefonata', 'L’ultima telefonata', 'stato', 0, { terrain: 'legno', modus: 'eolio', hush: 0.8, lumina: 'soffuse',
      levels: { m_telefono: 0.3, m_pendolo: 0.25, m_vento: 0.15, m_respiro: 0.12 }, set: { lumen: 0.25, nastro: 0.4, distantia: 0.6 }, libra: 0.82,
      pal: { bg: [9, 9, 10], accent: [214, 206, 200], second: [110, 104, 110] }, motif: { lights: 0.2, motes: 0.4 },
      clues: ['Era una telefonata come le altre.', 'Ti ha chiesto se avevi mangiato.', 'Hai detto: ci sentiamo domenica.', 'Non sapevi che era l’ultima.', 'Nessuno lo sa mai.', 'Se l’avessi saputo, avresti detto lo stesso. Forse va bene così.'],
      ora: 'Il telefono in mano, la voce dall’altra parte un po’ stanca. Parlate del tempo, della spesa, di niente.',
      allora: '' }),
    // ——————————————————————— LA CASA ABBANDONATA
    N('stanza_specchi', 'La stanza degli specchi', 'luogo', 0, { terrain: 'legno', modus: 'hirajoshi', hush: 0.75, lumina: 'torcia',
      levels: { m_sussurri: 0.3, m_carezza: 0.15, m_goccia: 0.15, m_respiro: 0.15 }, set: { lumen: 0.2, distantia: 0.6, crypta: 0.8, mercurius: 0.6 }, libra: 0.8,
      pal: { bg: [6, 6, 7], accent: [214, 214, 226], second: [100, 100, 120] }, motif: { doubt: 0.6, glass: 0.6 },
      ora: 'Gli specchi sono tutti coperti da lenzuola, tranne uno. Nella stanza c’è solo la tua torcia, ma nello specchio la luce è due.',
      allora: 'Si coprivano gli specchi quando moriva qualcuno, perché l’anima non si confondesse. Questo, chissà perché, l’hanno lasciato scoperto.' }),
    // ——————————————————————— IL MANICOMIO E GLI OSPEDALI
    N('pronto_soccorso', 'La sala d’attesa del pronto soccorso', 'stato', 0, { terrain: 'pietra', modus: 'eolio', hush: 0.5, lumina: 'accese',
      levels: { m_ronzio: 0.4, m_passi: 0.3, m_voci: 0.15, m_monitor: 0.12, m_telefono: 0.08 }, set: { lumen: 0.2, nastro: 0.2 }, libra: 0.7,
      pal: { bg: [10, 11, 11], accent: [214, 230, 226], second: [110, 130, 126] }, motif: { corridor: 0.5, fever: 0.3 },
      clues: ['Le sedie di plastica attaccate l’una all’altra.', 'Un distributore di caffè che non funziona.', 'Un numero sul tabellone, che non è mai il tuo.', 'Una porta che si apre: tutti alzano la testa.', 'Sono passate quattro ore. Nessuno ti dice niente.'],
      ora: 'Il neon, il pavimento lucido, l’odore di disinfettante. Aspetti notizie di qualcuno che è di là, dietro le porte che si aprono da sole.',
      allora: '' }),
    N('ospizio', 'L’ospizio', 'luogo', 0, { terrain: 'pietra', modus: 'eolio', hush: 0.7, lumina: 'soffuse',
      levels: { m_radio: 0.15, m_pendolo: 0.3, m_passi: 0.15, m_voci: 0.12, m_tossisce: 0, m_ronzio: 0.15 }, set: { lumen: 0.25, nastro: 0.4, oblio: 0.5 }, libra: 0.78,
      pal: { bg: [11, 10, 10], accent: [220, 206, 196], second: [120, 110, 106] }, motif: { windows: 0.5, motes: 0.5, corridor: 0.3 },
      clues: ['Una signora chiede a tutti che giorno è.', 'Un uomo tiene in mano una fotografia, sempre la stessa.', 'La televisione accesa nella sala, senza volume.', 'La domenica qualcuno viene. Non per tutti.', 'Davanti alla finestra, le sedie a rotelle in fila, girate verso il cancello.'],
      ora: 'Le poltrone di finta pelle, l’orologio grande, il carrello del tè delle quattro. Gli occhi di tutti guardano verso la porta.',
      allora: '' }),
    // ——————————————————————— IL CIMITERO DI NOTTE
    N('fuochi_fatui', 'I fuochi fatui', 'luogo', 0, { terrain: 'ghiaia', modus: 'armonici', hush: 0.7, lumina: 'soffuse', candles: true,
      levels: { m_grilli: 0.35, m_civetta: 0.2, m_vento: 0.25, m_canto: 0.08, m_carezza: 0.12, m_foglie: 0.15 }, set: { lumen: 0.3, aether: 0.75, distantia: 0.7, crypta: 0.85 }, libra: 0.82,
      pal: { bg: [4, 6, 8], accent: [150, 220, 255], second: [60, 110, 150] }, motif: { wisps: 1, tombs: 0.6 },
      ora: 'Il cimitero di notte. Tra le tombe si accendono piccole fiamme azzurre, senza calore, che salgono a mezz’aria e si spostano piano, come se cercassero qualcuno.',
      allora: 'La scienza dice che è un gas. Tua nonna diceva che sono le anime che fanno un giro. Stanotte credi a lei.' }),
    // ——————————————————————— LA STAZIONE
    N('addio', 'L’addio sul binario', 'stato', 0, { terrain: 'pietra', modus: 'eolio', hush: 0.45, lumina: 'soffuse',
      levels: { m_treno: 0.45, m_voci: 0.15, m_passi: 0.2, m_vento: 0.2, m_campane: 0.06 }, set: { lumen: 0.3, distantia: 0.5 }, libra: 0.72,
      pal: { bg: [9, 9, 11], accent: [210, 206, 214], second: [100, 100, 120] }, motif: { train: 0.6, tears: 0.3 },
      clues: ['Il fischio del capotreno.', 'Le porte che si chiudono con un soffio.', 'Una mano contro il vetro.', 'Il treno parte piano, poi sempre più forte.', 'Resti finché non si vede più niente. Poi resti ancora un po’.'],
      ora: 'Il binario, la valigia, un abbraccio troppo corto. Ci si dice le cose più importanti in fretta, mentre l’altoparlante annuncia un ritardo.',
      allora: '' }),
    N('binario_morto', 'Il binario morto', 'luogo', 0, { terrain: 'ghiaia', modus: 'insen', hush: 0.6, lumina: 'soffuse',
      levels: { m_vento: 0.4, m_grilli: 0.3, m_scricchiolio: 0.15, m_treno: 0.06 }, set: { lumen: 0.25, distantia: 0.7, oblio: 0.5 }, libra: 0.78,
      pal: { bg: [8, 8, 7], accent: [200, 190, 170], second: [100, 90, 80] }, motif: { train: 0.3, ruin: 0.6, path: 0.5 },
      ora: 'Un binario che finisce contro un respingente arrugginito, in mezzo all’erba alta. Sopra c’è un vagone fermo da decenni, con i finestrini rotti e i sedili di velluto.',
      allora: 'Ci salivi e facevi finta di partire. Sei andato lontanissimo, senza muoverti di un metro.' }),
    // ——————————————————————— LE FESTE
    N('sedia_vuota', 'La sedia vuota a Natale', 'stato', 0, { terrain: 'legno', modus: 'eolio', hush: 0.6, lumina: 'candele',
      levels: { m_stoviglie: 0.3, m_voci: 0.2, m_campane: 0.2, m_camino: 0.25, m_carillon: 0.12 }, set: { lumen: 0.35, velum: 0.4 }, libra: 0.75,
      pal: { bg: [12, 9, 8], accent: [240, 200, 140], second: [150, 60, 50] }, motif: { candles: 0.7, lights: 0.5 },
      clues: ['La tavola apparecchiata come sempre.', 'Qualcuno ha messo un piatto in più, per abitudine.', 'Nessuno lo toglie.', 'Si ride, si parla, si passa il pane.', 'Ogni tanto, tutti guardano quella sedia, e poi fanno finta di niente.'],
      ora: 'Il pranzo di Natale, la tovaglia rossa, le luci dell’albero che lampeggiano. Una sedia è rimasta vuota, e quest’anno nessuno l’ha spostata.',
      allora: '' }),
    N('compleanno_solo', 'Il compleanno da solo', 'stato', 0, { terrain: 'legno', modus: 'dorico', hush: 0.8, lumina: 'candele',
      levels: { m_pendolo: 0.25, m_candele: 0.25, m_festa: 0.06, m_tubature: 0.08 }, set: { lumen: 0.3, distantia: 0.6, oblio: 0.3 }, libra: 0.82,
      pal: { bg: [10, 9, 9], accent: [240, 206, 170], second: [140, 100, 100] }, motif: { candles: 0.6 },
      ora: 'Una fetta di torta comprata al bar, una candelina sola. Il telefono sul tavolo, a faccia in su. Da lontano, la festa di qualcun altro.',
      allora: 'Esprimi un desiderio lo stesso. Soffi piano, come se ci fosse qualcuno da non svegliare.' }),
    N('cane_vecchio', 'Il cane vecchio', 'stato', 0, { terrain: 'erba', modus: 'pentatonico', hush: 0.8, peace: 70, lumina: 'accese',
      levels: { m_respiro: 0.3, m_uccelli: 0.2, m_vento: 0.15, m_cani: 0.0, m_carezza: 0.2 }, set: { lumen: 0.4, velum: 0.5 }, libra: 0.85, bpm: 0.3,
      pal: { bg: [12, 11, 9], accent: [236, 214, 176], second: [150, 120, 90] }, motif: { sun: 0.4, haze: 0.4 },
      clues: ['Non corre più al cancello quando arrivi.', 'Ma la coda batte ancora sul pavimento.', 'Dorme quasi tutto il giorno, al sole.', 'Ti appoggia il muso sulla gamba.', 'Ti guarda come ti ha sempre guardato: come se fossi la cosa migliore del mondo.'],
      ora: 'Il cane vecchio sdraiato nell’ultima macchia di sole del giardino. Il muso grigio, il respiro lento. Ti siedi accanto a lui sull’erba.',
      allora: '' }),
    // ——————————————————————— IL NULLA
    N('campo_nulla', 'Il campo senza fine', 'luogo', 0, { terrain: 'erba', modus: 'armonici', hush: 0.7, peace: 90, lumina: 'soffuse',
      levels: { m_vento: 0.45, m_grilli: 0.2, m_foglie: 0.15 }, set: { lumen: 0.4, aether: 0.8, velum: 0.5, crypta: 0.9 }, libra: 0.88,
      pal: { bg: [10, 11, 12], accent: [220, 224, 230], second: [130, 140, 150] }, motif: { path: 1, haze: 0.5 },
      ora: 'Un campo d’erba bassa che arriva fino all’orizzonte, da ogni parte. Nessuna casa, nessun albero, nessun palo. Il cielo è grandissimo. Cammini.',
      allora: 'Non stai andando da nessuna parte, e per la prima volta non ti importa. Camminare basta.' }),
    N('strada_nulla', 'La strada che non porta a niente', 'luogo', 0, { terrain: 'ghiaia', modus: 'dorico', hush: 0.7, lumina: 'soffuse',
      levels: { m_vento: 0.4, m_grilli: 0.25, m_motore: 0.05 }, set: { lumen: 0.35, aether: 0.6, distantia: 0.8 }, libra: 0.85,
      pal: { bg: [10, 10, 10], accent: [214, 210, 200], second: [120, 116, 110] }, motif: { path: 1, fog: 0.3 },
      ora: 'Una strada asfaltata, dritta, con le righe bianche, in mezzo al nulla. Nessun cartello. Ogni tanto un paracarro. Finisce, all’improvviso, nell’erba.',
      allora: 'Qualcuno l’aveva progettata per arrivare da qualche parte. Poi ha cambiato idea. Anche le strade, a volte, si arrendono.' }),
    N('pensilina', 'La fermata in mezzo ai campi', 'luogo', 0, { terrain: 'ghiaia', modus: 'eolio', hush: 0.75, lumina: 'soffuse',
      levels: { m_vento: 0.35, m_grilli: 0.3, m_motore: 0.12, m_pioggia: 0.1 }, set: { lumen: 0.3, distantia: 0.7 }, libra: 0.84,
      pal: { bg: [9, 9, 10], accent: [214, 206, 180], second: [110, 110, 100] }, motif: { path: 0.5, lights: 0.3 },
      ora: 'Una pensilina di vetro e ferro, sola, accanto a una strada di campagna. L’orario appeso è illeggibile. Ti siedi sulla panca e aspetti un autobus che forse non passa più.',
      allora: 'Aspettare qui è diverso: non speri che arrivi qualcosa. Ti godi solo l’attesa.' }),
    N('palo_luce', 'Un lampione nel nulla', 'luogo', 0, { terrain: 'ghiaia', modus: 'insen', hush: 0.8, lumina: 'spente',
      levels: { m_ronzio: 0.2, m_grilli: 0.35, m_vento: 0.25 }, set: { lumen: 0.3, distantia: 0.75 }, libra: 0.85,
      pal: { bg: [4, 4, 5], accent: [255, 214, 150], second: [120, 90, 60] }, motif: { door: 0.6, motes: 0.6 },
      ora: 'Buio da ogni parte, e un lampione solo che illumina un cerchio d’asfalto. Le falene ci girano intorno. Tu stai nel cerchio, e fuori non c’è niente.',
      allora: 'A volte la vita è così: un piccolo cerchio di luce, e il resto da indovinare. Basta restarci dentro, finché serve.' }),
    N('deserto_sale', 'La pianura di sale', 'luogo', 0, { terrain: 'sabbia', modus: 'armonici', hush: 0.9, peace: 50, lumina: 'accese',
      levels: { m_vento: 0.35, m_carezza: 0.15 }, set: { lumen: 0.45, aether: 0.85, chorus: 0.25, crypta: 0.95 }, libra: 0.92,
      pal: { bg: [14, 14, 15], accent: [244, 244, 250], second: [170, 180, 200] }, motif: { path: 0.6, sun: 0.3, haze: 0.6 },
      ora: 'Una distesa bianca e piatta, crepata in esagoni, che riflette il cielo. Non c’è eco, non c’è ombra. Il vento porta via anche i pensieri.',
      allora: 'Qui una volta c’era il mare. Se n’è andato, ha lasciato il suo sale, come una firma.' }),
    N('orizzonte', 'L’orizzonte', 'luogo', 0, { terrain: 'erba', modus: 'lidio', hush: 0.8, peace: 60, lumina: 'accese',
      levels: { m_vento: 0.3, m_uccelli: 0.15, m_carezza: 0.2 }, set: { lumen: 0.45, aether: 0.8, velum: 0.6, chorus: 0.3 }, libra: 0.9,
      pal: { bg: [13, 12, 12], accent: [250, 220, 190], second: [200, 150, 140] }, motif: { path: 0.8, sun: 0.6 },
      ora: 'Cammini verso l’orizzonte, e l’orizzonte si sposta. Non lo raggiungerai mai. Ma intanto il sole tramonta proprio lì, e tutto diventa rosa.',
      allora: 'Non serve arrivare. Serviva solo avere una direzione.' }),
    N('cammino_notte', 'Camminare di notte senza meta', 'stato', 0, { terrain: 'pietra', modus: 'dorico', hush: 0.6, lumina: 'soffuse',
      levels: { m_passi: 0.4, m_grilli: 0.3, m_cani: 0.1, m_motore: 0.08, m_vento: 0.2, m_richiamo: 0.06 }, set: { lumen: 0.3, distantia: 0.6 }, libra: 0.8,
      pal: { bg: [6, 7, 9], accent: [200, 206, 220], second: [90, 96, 120] }, motif: { path: 0.7, stars: 0.4, lights: 0.3 },
      clues: ['Sei uscito senza sapere dove andare.', 'Una via, poi un’altra.', 'Le case con le tapparelle abbassate.', 'Un gatto ti segue per un pezzo, poi cambia idea.', 'Torni a casa più leggero, senza aver risolto niente.'],
      ora: 'I tuoi passi sono l’unico rumore della strada. Non cerchi niente. Cammini perché fermarsi, stasera, sarebbe troppo.',
      allora: '' }),
    // ——————————————————————— LE TORRI · LA MONTAGNA · LA RINASCITA
    N('pascolo', 'Il pascolo', 'luogo', 1, { terrain: 'erba', modus: 'ionio', hush: 0.5, peace: 90, lumina: 'accese',
      levels: { m_campanacci: 0.55, m_vento: 0.35, m_uccelli: 0.25, m_ruscello: 0.15 }, set: { lumen: 0.4, aether: 0.6, crypta: 0.85 }, libra: 0.8,
      pal: { bg: [10, 12, 12], accent: [214, 236, 210], second: [110, 150, 140] }, motif: { mountain: 0.6, field: 0.5 },
      ora: 'Un prato in pendio, punteggiato di mucche. I campanacci suonano ognuno per conto suo, una musica che nessuno ha scritto e che non finisce mai.',
      allora: 'Il pastore ti ha offerto un pezzo di formaggio sulla punta del coltello. Non vi siete detti quasi niente. È stato uno dei pranzi più belli.' }),
    N('germoglio', 'Il germoglio', 'luogo', 1, { terrain: 'erba', modus: 'lidio', hush: 0.65, peace: 70, lumina: 'accese',
      levels: { m_uccelli: 0.35, m_ruscello: 0.15, m_vento: 0.15, m_carezza: 0.15 }, set: { lumen: 0.45, velum: 0.55, chorus: 0.25 }, libra: 0.85,
      pal: { bg: [11, 13, 11], accent: [210, 240, 190], second: [140, 190, 140] }, motif: { sprout: 1, sun: 0.3 },
      ora: 'Una crepa nell’asfalto, e dentro un filo verde che si fa strada. Nessuno l’ha piantato. Nessuno l’ha aiutato. È spuntato e basta.',
      allora: 'Dopo un inverno lungo, la prima cosa che rinasce non è mai quella che ti aspetti.' }),
    N('ricominciare', 'Ricominciare', 'stato', 1, { terrain: 'erba', modus: 'ionio', hush: 0.6, lumina: 'accese',
      levels: { m_uccelli: 0.3, m_passi: 0.2, m_vento: 0.15, m_campane: 0.1 }, set: { lumen: 0.45, velum: 0.5 }, libra: 0.8,
      pal: { bg: [12, 12, 11], accent: [240, 226, 190], second: [170, 160, 130] }, motif: { sprout: 0.5, sun: 0.5 },
      clues: ['Ti alzi presto, anche se non serve.', 'Apri le finestre.', 'Butti via una cosa che tenevi solo per dolore.', 'Esci a comprare il pane, e saluti il fornaio.', 'Non è passato. Ma oggi si può.'],
      ora: 'La mattina dopo. Niente è cambiato, eppure tutto ha un colore un po’ diverso. Fai una cosa piccola, poi un’altra.',
      allora: '' }),
    N('finestra_aperta', 'La finestra aperta', 'luogo', 1, { terrain: 'legno', modus: 'lidio', hush: 0.7, peace: 60, lumina: 'accese',
      levels: { m_uccelli: 0.35, m_vento: 0.25, m_campane: 0.12, m_bambini: 0.06 }, set: { lumen: 0.45, velum: 0.6, aether: 0.4 }, libra: 0.85,
      pal: { bg: [13, 13, 12], accent: [250, 236, 200], second: [190, 180, 150] }, motif: { beam: 0.6, motes: 0.5, sun: 0.3 },
      ora: 'Una stanza chiusa da troppo tempo. Apri la finestra, e l’aria entra tutta insieme, con il rumore della strada, gli uccelli, l’odore della pioggia di ieri.',
      allora: 'Non sapevi quanto ti mancava il mondo finché non l’hai fatto entrare.' }),
    N('perdono', 'Il perdono', 'stato', 1, { terrain: 'nuvola', modus: 'pentatonico', hush: 0.85, peace: 50, lumina: 'soffuse',
      levels: { m_carezza: 0.3, m_canto: 0.15, m_vento: 0.1 }, set: { lumen: 0.4, velum: 0.6, chorus: 0.35, aether: 0.5 }, libra: 0.9,
      pal: { bg: [12, 12, 13], accent: [236, 226, 236], second: [170, 160, 190] }, motif: { purify: 0.4, haze: 0.5 },
      ora: 'Non è dimenticare. È posare un peso che portavi da così tanto che pensavi fosse una parte di te. Le spalle, all’improvviso, sono più leggere.',
      allora: 'A volte la persona da perdonare eri tu.' }),
    N('prima_volta', 'La prima volta dopo tanto', 'stato', 1, { terrain: 'erba', modus: 'ionio', hush: 0.5, lumina: 'accese',
      levels: { m_voci: 0.2, m_bambini: 0.15, m_uccelli: 0.25, m_festa: 0.1, m_cuore: 0.15 }, set: { lumen: 0.45, velum: 0.45 }, libra: 0.75,
      pal: { bg: [13, 12, 11], accent: [250, 220, 170], second: [200, 150, 120] }, motif: { sun: 0.6, meet: 0.4 },
      ora: 'Hai riso. Una risata vera, di pancia, senza pensarci. Ti sei sorpreso da solo, come quando si sente la propria voce dopo una lunga malattia.',
      allora: 'Credevi di aver dimenticato come si fa. Il corpo, invece, se lo ricordava.' }),
    N('respiro_lungo', 'Il primo respiro profondo', 'stato', 1, { terrain: 'nuvola', modus: 'armonici', hush: 0.9, peace: 40, lumina: 'accese', spira: true,
      levels: { m_respiro: 0.3, m_vento: 0.2, m_carezza: 0.2 }, set: { lumen: 0.45, aether: 0.7, chorus: 0.3 }, libra: 0.92,
      pal: { bg: [12, 13, 14], accent: [226, 236, 250], second: [160, 180, 210] }, motif: { haze: 0.6, purify: 0.3 },
      ora: 'Inspiri, piano, fino in fondo, come non facevi da mesi. Trattieni. Poi lasci andare tutto. Il petto si apre come una finestra.',
      allora: 'Era lì da sempre, il respiro. Bastava ricordarsi di lasciarlo entrare.' }),
    // ——————————————————————— I TETTI · LA VETTA · IL CIELO
    N('rifugio_neve', 'Il rifugio nella neve', 'luogo', 2, { terrain: 'legno', modus: 'ionio', hush: 0.65, peace: 70, lumina: 'candele',
      levels: { m_camino: 0.45, m_vento: 0.45, m_stoviglie: 0.12, m_voci: 0.1 }, set: { lumen: 0.4, velum: 0.5 }, libra: 0.8,
      pal: { bg: [12, 10, 9], accent: [250, 200, 140], second: [140, 160, 200] }, motif: { snow: 0.6, candles: 0.5 },
      ora: 'Fuori la tormenta, dentro la stufa che scoppietta. Gli scarponi ad asciugare, le mani intorno a una tazza. La finestra è un quadrato di bianco che si muove.',
      allora: 'Il calore ha più senso quando fuori c’è tutto quel freddo. Forse anche la felicità.' }),
    N('ghiacciaio', 'Il ghiacciaio', 'luogo', 2, { terrain: 'neve', modus: 'armonici', hush: 0.6, lumina: 'accese',
      levels: { m_ghiaccio: 0.4, m_vento: 0.55, m_goccia: 0.2, m_ruscello: 0.12 }, set: { lumen: 0.4, aether: 0.85, crypta: 0.95 }, libra: 0.82,
      pal: { bg: [10, 13, 16], accent: [210, 240, 255], second: [100, 160, 210] }, motif: { ice: 0.8, mountain: 0.5 },
      ora: 'Un fiume di ghiaccio azzurro che scende lentissimo dalla montagna. Dentro si sente l’acqua che corre, e ogni tanto uno schianto lontano, come un tuono sepolto.',
      allora: 'Quando eri piccolo arrivava fino a valle. Adesso bisogna salire per trovarlo. Anche lui se ne sta andando, piano.' }),
    N('luna_piena', 'La luna piena sui tetti', 'luogo', 2, { terrain: 'tegole', modus: 'pentatonico', hush: 0.7, peace: 70, lumina: 'soffuse',
      levels: { m_grilli: 0.25, m_vento: 0.25, m_cani: 0.08, m_campane: 0.06 }, set: { lumen: 0.4, aether: 0.8, chorus: 0.2 }, libra: 0.85,
      pal: { bg: [7, 8, 12], accent: [230, 236, 255], second: [120, 130, 180] }, motif: { lake: 0.3, stars: 0.6, city: 0.3 },
      ora: 'La luna piena così grande che sembra appoggiata sul comignolo. I tetti diventano d’argento, i gatti escono a guardarla anche loro.',
      allora: 'La stessa luna la guarda chiunque tu abbia perso, ovunque sia. È l’unico posto dove vi incontrate ancora.' }),
    N('aquilone', 'L’aquilone', 'luogo', 2, { terrain: 'nuvola', modus: 'lidio', hush: 0.55, peace: 80, lumina: 'accese',
      levels: { m_vento: 0.55, m_uccelli: 0.2, m_bambini: 0.12, m_gabbiani: 0.05 }, set: { lumen: 0.45, aether: 0.7, velum: 0.5 }, libra: 0.82,
      pal: { bg: [12, 13, 15], accent: [240, 236, 220], second: [200, 120, 110] }, motif: { sun: 0.4, haze: 0.4, sprout: 0.0 },
      ora: 'Un aquilone rosso lassù, tirato da un filo sottilissimo che sparisce nel cielo. Il vento lo tiene su, tu lo tieni giù. Insieme fate una cosa bellissima.',
      allora: 'L’avete costruito con le canne e la carta velina, tu e il nonno. Non volava. Poi, all’improvviso, ha volato.' }),
    N('nuvole', 'Sopra le nuvole', 'luogo', 2, { terrain: 'nuvola', modus: 'armonici', hush: 0.85, peace: 50, lumina: 'accese',
      levels: { m_vento: 0.3, m_carezza: 0.25, m_canto: 0.1 }, set: { lumen: 0.5, aether: 0.9, chorus: 0.35, velum: 0.6 }, libra: 0.92,
      pal: { bg: [14, 14, 16], accent: [250, 246, 240], second: [200, 210, 230] }, motif: { haze: 1, sun: 0.4 },
      ora: 'Un mare bianco e morbido sotto di te, che arriva fino all’orizzonte. Sopra, il cielo più blu che tu abbia mai visto. Laggiù, sotto, piove su qualcuno.',
      allora: 'C’è sempre il sole, sopra le nuvole. Anche nei giorni peggiori. Bisogna solo salire abbastanza.' }),
    N('aurora_boreale', 'L’aurora', 'luogo', 3, { terrain: 'neve', modus: 'armonici', hush: 0.8, peace: 60, lumina: 'spente',
      levels: { m_vento: 0.3, m_ghiaccio: 0.12, m_carezza: 0.3, m_canto: 0.12 }, set: { lumen: 0.5, aether: 0.9, chorus: 0.4, velum: 0.6 }, libra: 0.92,
      pal: { bg: [3, 6, 8], accent: [140, 255, 200], second: [170, 100, 230] }, motif: { rose: 0.3, stars: 0.6, nebula: 0.5 },
      ora: 'Il cielo si muove: tende verdi e viola che ondeggiano senza rumore, si piegano, si aprono, si richiudono. Ti sembra di sentirle cantare, ma è solo il tuo cuore.',
      allora: 'Si diceva che fossero i morti che danzano per farsi vedere da chi è rimasto.' }),
    // ——————————————————————— IL SOTTOSUOLO
    N('cantina', 'La cantina dei nonni', 'luogo', -1, { terrain: 'pietra', modus: 'dorico', hush: 0.75, lumina: 'torcia',
      levels: { m_goccia: 0.3, m_tubature: 0.2, m_scricchiolio: 0.15, m_passi: 0.08 }, set: { lumen: 0.25, crypta: 0.8, oblio: 0.4 }, libra: 0.8,
      pal: { bg: [9, 8, 7], accent: [214, 180, 140], second: [110, 80, 60] }, motif: { clutter: 0.6, motes: 0.6 },
      ora: 'Le damigiane impagliate, le file di barattoli di pomodoro con la data scritta a mano, le mele sulla paglia. L’odore di vino e di terra. Fa fresco anche d’agosto.',
      allora: 'Ti mandavano giù a prendere una bottiglia, e tu correvi su per le scale, con la paura del buio alle spalle.' }),
    N('grotta', 'La grotta dietro la cascata', 'luogo', -1, { terrain: 'pietra', modus: 'armonici', hush: 0.5, lumina: 'torcia',
      levels: { m_goccia: 0.45, m_ruscello: 0.35, m_vento: 0.15, m_bolle: 0.08 }, set: { lumen: 0.3, crypta: 0.95, aether: 0.6 }, libra: 0.75,
      pal: { bg: [6, 8, 9], accent: [180, 220, 214], second: [70, 110, 110] }, motif: { glass: 0.4, well: 0.4, underwater: 0.2 },
      ora: 'Hai attraversato il velo d’acqua. Dietro c’è una grotta, buia e fresca, e il rumore della cascata arriva ovattato, come dall’altra parte di un sogno.',
      allora: 'Sulle pareti, segni rossi di mani: qualcuno, migliaia di anni fa, ha voluto dire: io c’ero.' }),
    N('catacombe', 'Le catacombe', 'luogo', -1, { terrain: 'pietra', modus: 'insen', hush: 0.7, lumina: 'candele',
      levels: { m_goccia: 0.3, m_canto: 0.15, m_sussurri: 0.15, m_passi: 0.12, m_candele: 0.2 }, set: { lumen: 0.25, crypta: 0.95, distantia: 0.7 }, libra: 0.8,
      pal: { bg: [7, 6, 6], accent: [220, 180, 130], second: [110, 80, 60] }, motif: { loculi: 0.5, candles: 0.5, corridor: 0.4 },
      ora: 'Gallerie scavate nel tufo, con le nicchie una sopra l’altra. Una candela, i nomi graffiati in latino, piccoli simboli: un pesce, una colomba, un’ancora.',
      allora: 'Chi li ha sepolti qui sperava in qualcosa. Duemila anni dopo, la loro speranza è ancora scritta sul muro.' }),
    N('ossario', 'L’ossario', 'luogo', -1, { terrain: 'pietra', modus: 'eolio', hush: 0.85, lumina: 'candele', candles: true,
      levels: { m_goccia: 0.2, m_canto: 0.12, m_candele: 0.25 }, set: { lumen: 0.25, crypta: 0.95, oblio: 0.5 }, libra: 0.85,
      pal: { bg: [8, 7, 7], accent: [226, 214, 196], second: [120, 110, 100] }, motif: { loculi: 0.4, candles: 0.6 },
      ora: 'Una stanza bassa sotto la chiesa, dove riposano insieme quelli di cui nessuno ricorda più il nome. Nessuna fotografia, nessuna data. Solo un lumino, sempre acceso.',
      allora: 'Alla fine si torna tutti uguali. Non fa paura, qui: fa quasi pace.' }),
    // ——————————————————————— L'ABISSO
    N('relitto', 'Il relitto', 'luogo', -2, { terrain: 'acqua', modus: 'insen', hush: 0.75, lumina: 'torcia',
      levels: { m_balena: 0.3, m_bolle: 0.3, m_scricchiolio: 0.2, m_campane: 0.05 }, set: { lumen: 0.25, crypta: 0.95, distantia: 0.8, oblio: 0.5 }, libra: 0.85,
      pal: { bg: [2, 5, 7], accent: [130, 180, 190], second: [40, 70, 80] }, motif: { deep: 0.8, underwater: 0.6 },
      ora: 'Una nave adagiata sul fondo, il nome ancora leggibile sulla prua. I pesci entrano ed escono dagli oblò. Nella sala da pranzo i piatti sono ancora impilati.',
      allora: 'Qualcuno, quella sera, aveva prenotato un tavolo. Il mare ha apparecchiato per sempre.' })
  ];
  NEW.forEach(p => { if (!ATH.PLACE[p.id]) { ATH.PLACES.push(p); ATH.PLACE[p.id] = p; } });

  // Ora · Allora: i suoni di quando questi luoghi erano vivi
  const AL = {
    mulino: { m_macchine: 0.3, m_ruscello: 0.2 }, casa_venduta: { m_voci: 0.25, m_stoviglie: 0.2, m_bambini: 0.12 },
    binario_morto: { m_treno: 0.4 }, spiaggia_inverno: { m_bambini: 0.4, m_voci: 0.25, m_radio: 0.15 }, borgo: { m_voci: 0.25, m_bambini: 0.15 },
    ospizio: { m_voci: 0.2 }, sedia_vuota: { m_voci: 0.2 }, cane_vecchio: { m_cani: 0.3, m_bambini: 0.15 }, cantina: { m_voci: 0.12, m_passi: 0.15 }
  };
  Object.keys(AL).forEach(id => { if (ATH.PLACE[id]) ATH.PLACE[id].alloraLevels = AL[id]; });

  // i suoni giusti per ogni luogo: grilli, rane, foglie, civette, acqua
  const AMB = {
    stelle: { m_grilli: 0.4, m_foglie: 0.1 }, lorenzo: { m_grilli: 0.35 }, campagna: { m_grilli: 0.3, m_foglie: 0.15 }, bosco: { m_foglie: 0.35, m_civetta: 0.2 },
    conca: { m_foglie: 0.35 }, bosco_profondo: { m_foglie: 0.4, m_civetta: 0.3 }, cimitero: { m_grilli: 0.25, m_civetta: 0.1 }, monumentale: { m_foglie: 0.2, m_civetta: 0.08 },
    giardino: { m_uccelli: 0.3, m_ruscello: 0.18 }, alba: { m_uccelli: 0.35 }, strade_nebbia: { m_grilli: 0.25, m_rane: 0.08 }, parco_giochi: { m_foglie: 0.2 },
    citta_abbandonata: { m_foglie: 0.12 }, manicomio_abb: { m_foglie: 0.1 }, sentiero: { m_campanacci: 0.18, m_ruscello: 0.15, m_foglie: 0.15 }, baita: { m_foglie: 0.12 },
    lago: { m_grilli: 0.35, m_rane: 0.4 }, palude: { m_rane: 0.6 }, neve: { m_vento: 0.25 }, estate: { m_cicale: 0.6 }, fuga: { m_foglie: 0.25 },
    felicita: { m_uccelli: 0.25 }, domenica: { m_campane: 0.3 }, fiera: { m_festa: 0.3 }, casa: { m_foglie: 0.1 }, cortile: { m_foglie: 0.12 },
    vetta: { m_campanacci: 0.05 }, risalita: { m_ruscello: 0.1 }, ospedale_abb: { m_goccia: 0.25 }
  };
  Object.keys(AMB).forEach(id => { const p = ATH.PLACE[id]; if (!p) return; Object.keys(AMB[id]).forEach(m => { p.levels[m] = Math.max(p.levels[m] || 0, AMB[id][m]); }); });
  // i nomi di suoni che non esistono non devono fare danni
  ATH.PLACES.forEach(p => Object.keys(p.levels || {}).forEach(m => { if (ATH.MEM_IDS.indexOf(m) < 0) delete p.levels[m]; }));
})(window.ATH);
