/* ATHANOR — LA MENTE. I luoghi che non stanno sulla terra: la folla che ti
   guarda (o forse no), l'ufficio dove tutti sanno cosa fare tranne te, le
   stanze che fanno domande, il dormiveglia, il cassetto delle cose ritrovate,
   la sala dei ritorni, la testa quando si sente fuori posto. E le capsule del
   tempo: luoghi nascosti dove ritrovi qualcosa, o qualcuno, senza sapere se è
   un ricordo, un sogno, o se è successo davvero.
   un luogo moderatamente sicuro */
window.ATH = window.ATH || {};

(function (ATH) {
  const M = (id, name, kind, o) => Object.assign({ id, name, kind, level: 0, mind: true, exits: [], motif: {} }, o);
  const DREAM = { bg: [10, 9, 12], accent: [226, 214, 236], second: [150, 130, 170] };
  const NEW = [
    // ——————————————————————— LA FOLLA
    M('folla', 'La piazza affollata', 'luogo', { terrain: 'pietra', modus: 'hirajoshi', hush: 0.25, lumina: 'accese', press: 45,
      levels: { m_voci: 0.45, m_passi: 0.4, m_festa: 0.15, m_bambini: 0.12, m_campane: 0.08 }, set: { lumen: 0.25, distantia: 0.25 }, libra: 0.6,
      pal: { bg: [12, 11, 10], accent: [230, 214, 196], second: [140, 120, 110] }, motif: { crowd: 1 },
      clues: ['Hai detto una cosa, prima. Una cosa qualunque.', 'Perché ho detto questa cosa?', 'Avrei dovuto rispondere in un altro modo.', 'Quello là ti ha guardato. Ha visto.', 'Adesso penseranno male di me.', 'Ho fatto una figuraccia.', 'Ci ripenserai stanotte. E domani.'],
      ora: 'Una piazza piena, un giorno di festa. Tutti parlano, ridono, si urtano. Nessuno ti guarda davvero. Eppure.',
      allora: '' }),
    M('festa_folla', 'La festa dove non conosci nessuno', 'stato', { terrain: 'legno', modus: 'dorico', hush: 0.3, lumina: 'soffuse', press: 40,
      levels: { m_festa: 0.5, m_voci: 0.4, m_stoviglie: 0.2, m_grammofono: 0.15 }, set: { lumen: 0.3, distantia: 0.3, nastro: 0.2 }, libra: 0.62,
      pal: { bg: [12, 10, 10], accent: [240, 200, 160], second: [150, 90, 100] }, motif: { crowd: 0.8, lights: 0.5 },
      clues: ['Hai un bicchiere in mano, così sembri occupato.', 'Ti avvicini a un gruppo. Ridono di una cosa che non sai.', 'Qualcuno ti chiede: e tu cosa fai?', 'Rispondi. Ti esce una frase strana.', 'Sorridono per educazione.', 'Guardi l’ora. Sono passati sei minuti.'],
      ora: 'Le voci che si sovrappongono, la musica troppo alta, le risate. Stai in piedi vicino al muro, con un bicchiere che non bevi.',
      allora: '' }),
    M('palco', 'Il palco', 'stato', { terrain: 'legno', modus: 'insen', hush: 0.6, lumina: 'spente', press: 30,
      levels: { m_cuore: 0.45, m_respiro: 0.35, m_acufene: 0.2, m_voci: 0.12, m_ronzio: 0.2 }, set: { lumen: 0.2, distantia: 0.3 }, libra: 0.75, bpm: 0.7,
      pal: { bg: [5, 5, 6], accent: [255, 246, 220], second: [120, 110, 100] }, motif: { beam: 1, crowd: 0.5 },
      clues: ['Un faro bianco ti prende in pieno.', 'Di là, nel buio, centinaia di occhi.', 'Apri la bocca e non esce niente.', 'Il cuore nelle orecchie.', 'Qualcuno, in fondo, tossisce.'],
      ora: 'Sei in mezzo alla luce. Tutto il resto è buio, e nel buio c’è gente che aspetta che tu dica qualcosa.',
      allora: '' }),
    // ——————————————————————— L'IMPOSTORE
    M('ufficio', 'L’ufficio dove tutti sanno cosa fare', 'luogo', { terrain: 'pietra', modus: 'dorico', hush: 0.35, lumina: 'accese', press: 60,
      levels: { m_telefono: 0.35, m_passi: 0.3, m_voci: 0.3, m_ronzio: 0.35, m_pendolo: 0.15 }, set: { lumen: 0.2, nastro: 0.15, distantia: 0.35 }, libra: 0.62,
      pal: { bg: [11, 12, 12], accent: [210, 224, 226], second: [110, 130, 134] }, motif: { crowd: 0.5, corridor: 0.4 },
      clues: ['Tutti battono sulle tastiere, sicuri.', 'Usano parole che fingi di conoscere.', 'Ti chiedono un parere. Annuisci.', 'Hai fatto bene il lavoro. È stato un caso.', 'Prima o poi qualcuno se ne accorgerà.', 'Che non sei capace. Che fingi.'],
      ora: 'Scrivanie in fila, il neon, i telefoni. Ognuno sa esattamente cosa deve fare. Tu guardi lo schermo e cerchi di sembrare uno di loro.',
      allora: '' }),
    M('esame', 'L’esame', 'stato', { terrain: 'legno', modus: 'eolio', hush: 0.7, lumina: 'accese', press: 50,
      levels: { m_pendolo: 0.45, m_fruscio: 0.3, m_cuore: 0.25, m_ronzio: 0.15 }, set: { lumen: 0.2, distantia: 0.4 }, libra: 0.8, bpm: 0.6,
      pal: { bg: [11, 11, 11], accent: [220, 220, 214], second: [120, 120, 116] }, motif: { motes: 0.5, corridor: 0.3 },
      ask: [
        { q: 'Quanto fa la cosa che tutti sanno?', a: [{ t: 'Lo so', say: 'Ne sei sicuro? Gli altri hanno scritto un’altra cosa.' }, { t: 'Non lo so', say: 'Nessuno lo sa davvero. Ma loro fanno finta meglio di te.', f: 'impostore' }, { t: 'Lascio in bianco', say: 'Il foglio bianco ti guarda.', mus: { m_acufene: 0.04 } }] },
        { q: 'Hai mai finto di sapere qualcosa?', a: [{ t: 'Sì', say: 'Anche adesso?', f: 'impostore' }, { t: 'No', say: 'Allora perché ti tremano le mani?' }, { t: 'Lo sto facendo adesso', say: 'Grazie per averlo detto. Nessuno lo dice.', mus: { velum: 0.05 } }] }
      ],
      ora: 'Un’aula silenziosa, i banchi distanziati, l’orologio sopra la lavagna. Gli altri scrivono senza fermarsi. Tu hai letto la prima domanda sei volte.',
      allora: '' }),
    M('riunione', 'La riunione', 'stato', { terrain: 'pietra', modus: 'dorico', hush: 0.45, lumina: 'accese', press: 45,
      levels: { m_voci: 0.4, m_ronzio: 0.25, m_pendolo: 0.2, m_cuore: 0.15 }, set: { lumen: 0.2, distantia: 0.3 }, libra: 0.68,
      pal: { bg: [11, 11, 12], accent: [214, 218, 230], second: [110, 116, 134] }, motif: { crowd: 0.6 },
      clues: ['Il giro di tavolo si avvicina.', 'Ripeti nella testa cosa dirai.', 'Tocca a te. Dici una frase. Va bene.', 'Ma la rigiri per tutto il resto della riunione.', 'Forse dovevo stare zitto.'],
      ora: 'Un tavolo lungo, dieci persone che parlano a turno con sicurezza. Prendi appunti per avere qualcosa da fare con le mani.',
      allora: '' }),
    M('complimento', 'Il complimento', 'stato', { terrain: 'nuvola', modus: 'lidio', hush: 0.7, lumina: 'accese',
      levels: { m_voci: 0.12, m_carezza: 0.2, m_cuore: 0.15 }, set: { lumen: 0.4, velum: 0.4 }, libra: 0.82,
      pal: { bg: [12, 12, 12], accent: [240, 230, 210], second: [170, 160, 150] }, motif: { sun: 0.3, haze: 0.4 },
      clues: ['Qualcuno ti dice: hai fatto un ottimo lavoro.', 'Rispondi subito: ma no, è stato facile.', 'Pensi: non sa com’è andata davvero.', 'Pensi: è stata fortuna.', 'E se invece avesse ragione lui?'],
      ora: 'Una frase gentile, detta di passaggio. Ti scivola addosso come acqua su un vetro. Non riesci a tenerla.',
      allora: '' }),
    M('sportello', 'Lo sportello', 'luogo', { terrain: 'pietra', modus: 'insen', hush: 0.55, lumina: 'accese',
      levels: { m_ronzio: 0.35, m_passi: 0.2, m_telefono: 0.15, m_pendolo: 0.2 }, set: { lumen: 0.2, nastro: 0.3 }, libra: 0.72,
      pal: { bg: [11, 12, 11], accent: [206, 220, 210], second: [110, 126, 116] }, motif: { corridor: 0.5 },
      ask: [
        { q: 'Motivo della visita?', a: [{ t: 'Non lo so', say: 'Compili il modulo B, allora.' }, { t: 'Cerco una persona', say: 'Non risulta. Ma torni domani.', f: 'cerca' }, { t: 'Sono qui per sbaglio', say: 'Come tutti, signore. Come tutti.' }] },
        { q: 'Firma qui. Il suo nome com’era?', a: [{ t: 'Lo scrivo', say: 'Questa non è la sua firma.' }, { t: 'Non ricordo', say: 'Capita. Si sieda, la chiamiamo noi.', mus: { oblio: 0.05 } }, { t: 'Quale dei due?', say: 'Il primo che le viene.', f: 'doppio' }] }
      ],
      ora: 'Uno sportello con il vetro, un numero rosso che non cambia mai, una fila di persone che aspettano tutte un modulo diverso.',
      allora: '' }),
    // ——————————————————————— LE DOMANDE
    M('stanza_domande', 'La stanza delle domande', 'luogo', { terrain: 'legno', modus: 'armonici', hush: 0.85, lumina: 'soffuse',
      levels: { m_pendolo: 0.25, m_carezza: 0.15, m_fruscio: 0.15 }, set: { lumen: 0.3, velum: 0.4, aether: 0.5 }, libra: 0.88,
      pal: DREAM, motif: { dream: 0.5, motes: 0.4 },
      ask: [
        { q: 'Qual è il tuo primo ricordo?', a: [{ t: 'Una luce', say: 'Una luce. Sei sicuro che fosse tua?', f: 'luce' }, { t: 'Una voce', say: 'Una voce. Te la ricordi, o te l’hanno raccontata?', f: 'voce' }, { t: 'Non lo so', say: 'Non saperlo è già un ricordo.', f: 'nonso' }] },
        { q: 'Se potessi tornare a un giorno solo, quale sceglieresti?', a: [{ t: 'Un giorno qualsiasi d’estate', say: 'Proprio quello che non avevi notato.', mus: { m_cicale: 0.05 } }, { t: 'Il giorno prima', say: 'Del giorno prima di cosa? Lo sai solo tu.', f: 'prima' }, { t: 'Nessuno', say: 'È la risposta giusta. O la più triste.' }] },
        { q: 'Chi ti manca di più, adesso?', a: [{ t: 'Lo so', say: 'Allora non serve dirlo.', f: 'manca' }, { t: 'Non voglio dirlo', say: 'Va bene. Resta qui un momento.' }, { t: 'Tutti', say: 'Anche chi non hai mai conosciuto?', f: 'manca' }] },
        { q: 'Di che colore era la porta di casa dei nonni?', a: [{ t: 'Verde', say: 'Era marrone. O forse eri tu a vederla verde.' }, { t: 'Marrone', say: 'Era verde. Lo dicono tutti. Ma tu c’eri.' }, { t: 'Non ricordo', say: 'La porta sì, si ricorda di te.', f: 'porta' }] }
      ],
      ora: 'Una stanza vuota con una sedia sola. Nessuno parla, eppure le domande arrivano, una alla volta, scritte nell’aria.',
      allora: '' }),
    M('specchio_parla', 'Lo specchio che fa domande', 'luogo', { terrain: 'legno', modus: 'hirajoshi', hush: 0.8, lumina: 'candele',
      levels: { m_sussurri: 0.25, m_candele: 0.2, m_carezza: 0.12 }, set: { lumen: 0.25, mercurius: 0.6 }, libra: 0.85,
      pal: DREAM, motif: { doubt: 0.7, glass: 0.5 },
      ask: [
        { q: 'Chi sei, quando nessuno ti guarda?', a: [{ t: 'Lo stesso', say: 'Davvero? Allora perché ti sei girato?' }, { t: 'Un altro', say: 'E quale dei due è vero?', f: 'doppio' }, { t: 'Nessuno', say: 'Nessuno è già qualcuno.', mus: { aether: 0.05 } }] },
        { q: 'Hai sbagliato tutto?', a: [{ t: 'Sì', say: 'Tutto tutto? Anche quella volta?', f: 'sbagliato' }, { t: 'No', say: 'Allora perché ci pensi ogni notte?' }, { t: 'Non tutto', say: 'Questa sembra la risposta più vera.', mus: { velum: 0.05 } }] }
      ],
      ora: 'Uno specchio ovale con la cornice dorata. Il tuo riflesso ti guarda un istante più a lungo di quanto dovrebbe.',
      allora: '' }),
    M('confessionale', 'Il confessionale vuoto', 'luogo', { terrain: 'legno', modus: 'eolio', hush: 0.9, lumina: 'candele',
      levels: { m_candele: 0.25, m_organo: 0.08, m_respiro: 0.15 }, set: { lumen: 0.25, crypta: 0.85 }, libra: 0.88,
      pal: { bg: [9, 8, 8], accent: [230, 200, 160], second: [120, 90, 70] }, motif: { candles: 0.6 },
      ask: [
        { q: 'C’è qualcosa che non hai mai detto a nessuno?', a: [{ t: 'Sì', say: 'Dall’altra parte della grata, qualcuno respira. Poi più niente.', f: 'segreto' }, { t: 'No', say: 'Nessuno ci crede, ma va bene.' }, { t: 'Non qui', say: 'Hai ragione. Non qui.' }] },
        { q: 'Ti perdoni?', a: [{ t: 'Sì', say: 'Allora puoi alzarti.', f: 'perdono', mus: { velum: 0.05 } }, { t: 'Non ancora', say: 'Non ancora è già una strada.' }, { t: 'Per cosa?', say: 'Lo sai.' }] }
      ],
      ora: 'Il legno scuro, la tendina viola, la grata. Ti inginocchi. Dall’altra parte non c’è nessuno. Forse.',
      allora: '' }),
    M('bivio', 'Il bivio', 'luogo', { terrain: 'ghiaia', modus: 'dorico', hush: 0.7, lumina: 'soffuse',
      levels: { m_vento: 0.35, m_grilli: 0.25, m_campane: 0.06 }, set: { lumen: 0.3, distantia: 0.6 }, libra: 0.82,
      pal: { bg: [9, 9, 10], accent: [214, 210, 200], second: [110, 110, 116] }, motif: { path: 0.6, doubt: 0.3 },
      ask: [
        { q: 'Se allora avessi scelto l’altra strada?', a: [{ t: 'Sarei felice', say: 'Forse. O saresti qui a chiederti la stessa cosa.', f: 'altra' }, { t: 'Sarei un altro', say: 'E ti mancheresti?', f: 'altra' }, { t: 'Sarebbe uguale', say: 'Le strade si somigliano più di quanto si creda.' }] },
        { q: 'Destra o sinistra?', a: [{ t: 'Destra', say: 'Era quella giusta.' }, { t: 'Sinistra', say: 'Era quella giusta.' }, { t: 'Resto qui', say: 'Anche questa era giusta.', mus: { aether: 0.05 } }] }
      ],
      ora: 'Una strada bianca che si divide in due, uguali. Un cartello di legno senza scritte. Il vento muove l’erba in tutte e due le direzioni.',
      allora: '' }),
    // ——————————————————————— IL SOGNO E LE CAPSULE
    M('dormiveglia', 'Il dormiveglia', 'stato', { terrain: 'nuvola', modus: 'pentatonico', hush: 0.9, peace: 60, lumina: 'soffuse',
      levels: { m_respiro: 0.25, m_carillon: 0.2, m_fruscio: 0.2, m_pendolo: 0.12 }, set: { lumen: 0.35, velum: 0.5, oblio: 0.4, nastro: 0.3 }, libra: 0.9,
      pal: DREAM, motif: { dream: 1, haze: 0.5 },
      ora: 'Non dormi e non sei sveglio. I rumori della casa diventano altre cose: il frigorifero è un treno, la tenda è qualcuno. Le porte, qui, si aprono da sole.',
      allora: 'Restando abbastanza, a volte, si arriva da qualche parte dove non si era mai stati. O dove si era stati tanto tempo fa.' }),
    M('madre_sogno', 'Una donna in cucina', 'stato', { hidden: true, terrain: 'legno', modus: 'pentatonico', hush: 0.95, peace: 80, lumina: 'soffuse',
      secret: { at: ['dormiveglia', 'madre', 'fotografie'], linger: 45, chance: 0.12 },
      levels: { m_canto: 0.3, m_stoviglie: 0.12, m_carillon: 0.15, m_uccelli: 0.1 }, set: { lumen: 0.4, velum: 0.6, oblio: 0.5, chorus: 0.3 }, libra: 0.92,
      pal: { bg: [14, 12, 11], accent: [250, 226, 196], second: [200, 170, 160] }, motif: { dream: 1, sun: 0.4, motes: 0.5 },
      ora: 'Una cucina piena di sole. Una donna giovane ti dà le spalle e canticchia mentre lava qualcosa. Non si gira. Non serve: sai chi è.',
      allora: 'Non l’hai mai vista così. Non puoi ricordarla. Eppure conosci quella canzone.' }),
    M('casa_mai', 'Una casa dove non sei mai stato', 'luogo', { hidden: true, terrain: 'legno', modus: 'lidio', hush: 0.85, lumina: 'soffuse',
      secret: { at: ['dormiveglia', 'stanza_domande'], needs: 'luce', chance: 0.5 },
      levels: { m_pendolo: 0.25, m_carillon: 0.12, m_vento: 0.12 }, set: { lumen: 0.35, oblio: 0.5, nastro: 0.4 }, libra: 0.88,
      pal: DREAM, motif: { dream: 0.8, beam: 0.5, wallpaper: 0.3 },
      ora: 'Non ci sei mai stato. Lo sai. Eppure sai che dietro quella porta c’è un corridoio con un tappeto rosso, e in fondo una finestra rotonda. Apri. C’è.',
      allora: 'Forse era la luce del tuo primo ricordo. Forse l’hai sognata così tante volte da averla costruita.' }),
    M('voce_telefono', 'Una voce che dice il tuo nome', 'stato', { hidden: true, terrain: 'legno', modus: 'eolio', hush: 0.9, lumina: 'spente',
      secret: { at: ['dormiveglia', 'cabina', 'stanza_domande'], needs: 'voce', chance: 0.5 },
      levels: { m_telefono: 0.25, m_fruscio: 0.35, m_radio: 0.2 }, set: { lumen: 0.25, nastro: 0.6, distantia: 0.7 }, libra: 0.88,
      pal: DREAM, motif: { dream: 0.7, lights: 0.2 },
      clues: ['Il telefono squilla una volta sola.', 'Rispondi. Fruscio.', 'Poi una voce, lontanissima, dice il tuo nome.', 'Come lo diceva qualcuno, tanto tempo fa.', 'Riattaccano. O forse sei tu che ti svegli.'],
      ora: 'Una casa di notte, un telefono a rotella sul tavolino dell’ingresso.',
      allora: '' }),
    M('bambino_sconosciuto', 'Il bambino con il tuo maglione', 'stato', { hidden: true, terrain: 'erba', modus: 'insen', hush: 0.85, lumina: 'soffuse',
      secret: { at: ['fotografie', 'primo_ricordo', 'stanza_domande', 'parco_giochi'], needs: 'nonso', chance: 0.4 },
      levels: { m_bambini: 0.15, m_vento: 0.2, m_altalena: 0.25, m_carillon: 0.1 }, set: { lumen: 0.3, oblio: 0.55, nastro: 0.5 }, libra: 0.85,
      pal: DREAM, motif: { dream: 0.8, swing: 0.4 },
      ora: 'In fondo al prato c’è un bambino con un maglione a righe. Il tuo maglione, quello che ti aveva fatto la nonna. Ti guarda, serio. Poi torna a giocare.',
      allora: 'Sei tu? È un altro? Hai avuto davvero quel maglione, o lo hai visto in una fotografia?' }),
    M('festa_mai', 'Una festa che forse non c’è stata', 'stato', { hidden: true, terrain: 'erba', modus: 'lidio', hush: 0.7, lumina: 'candele',
      secret: { at: ['festa_finita', 'fiera', 'giugno'], linger: 35 },
      levels: { m_festa: 0.3, m_bambini: 0.2, m_grammofono: 0.2, m_grilli: 0.2 }, set: { lumen: 0.35, nastro: 0.6, oblio: 0.55 }, libra: 0.8,
      pal: { bg: [12, 10, 9], accent: [250, 210, 150], second: [200, 120, 110] }, motif: { dream: 0.6, lights: 0.8, fireflies: 0.4 },
      ora: 'Le lampadine colorate appese tra gli alberi, una tavolata lunga, qualcuno che balla scalzo sull’erba. Tutti ti salutano come se ti aspettassero.',
      allora: 'Chiedi a chi c’era. Nessuno se la ricorda. Ma tu hai ancora in bocca il sapore di quella torta.' }),
    M('padre_treno', 'Un uomo sul treno', 'stato', { hidden: true, terrain: 'legno', modus: 'eolio', hush: 0.8, lumina: 'soffuse',
      secret: { at: ['treno_notte', 'macchinina', 'citta_lontana'], chance: 0.2, linger: 50 },
      levels: { m_treno: 0.45, m_vento: 0.15, m_respiro: 0.1 }, set: { lumen: 0.3, oblio: 0.5, distantia: 0.6 }, libra: 0.85,
      pal: DREAM, motif: { dream: 0.7, train: 0.6 },
      ora: 'Nello scompartimento di fronte a te c’è un uomo che guarda fuori dal finestrino. Ha le mani di qualcuno che conosci. Scende alla stazione dopo, senza voltarsi.',
      allora: 'Potevi dire una parola. Non sapevi quale. Forse non era lui. Forse sì.' }),
    M('cassetto', 'Il cassetto', 'luogo', { terrain: 'legno', modus: 'pentatonico', hush: 0.85, lumina: 'soffuse',
      levels: { m_fruscio: 0.3, m_carillon: 0.15, m_pendolo: 0.15 }, set: { lumen: 0.3, oblio: 0.45, nastro: 0.4 }, libra: 0.86,
      pal: { bg: [11, 10, 9], accent: [230, 210, 180], second: [140, 120, 100] }, motif: { dream: 0.4, clutter: 0.5, motes: 0.6 },
      ora: 'Il cassetto del comò che non si apriva mai bene. Lo tiri, si incastra, poi cede. Dentro, in fondo, c’è sempre qualcosa che non sapevi più di avere.',
      allora: 'Ogni volta che lo apri, il fondo è un po’ più lontano.' }),
    M('oggetto_perduto', 'La scatola di latta', 'luogo', { hidden: true, terrain: 'legno', modus: 'lidio', hush: 0.9, lumina: 'soffuse',
      secret: { at: ['cassetto', 'ripostiglio', 'soffitta'], linger: 40, chance: 0.3 },
      levels: { m_carillon: 0.35, m_fruscio: 0.2 }, set: { lumen: 0.35, oblio: 0.4 }, libra: 0.88,
      pal: { bg: [12, 10, 9], accent: [236, 196, 140], second: [160, 110, 80] }, motif: { dream: 0.5, motes: 0.6, clutter: 0.4 },
      clues: ['Una scatola di biscotti, di latta, ammaccata.', 'Dentro: tre biglie, una conchiglia, un tappo di bottiglia.', 'Un biglietto piegato: c’è scritto un nome con la tua calligrafia di bambino.', 'Non ricordi chi fosse.', 'Ma per qualcuno, un tempo, era un tesoro.'],
      ora: 'Il coperchio fa un rumore che conosci da sempre.',
      allora: '' }),
    M('quaderno', 'Il quaderno di seconda', 'luogo', { hidden: true, terrain: 'legno', modus: 'ionio', hush: 0.9, lumina: 'accese',
      secret: { at: ['cassetto', 'aula'], chance: 0.3, linger: 45 },
      levels: { m_fruscio: 0.35, m_bambini: 0.1, m_pendolo: 0.15 }, set: { lumen: 0.4, nastro: 0.4, oblio: 0.4 }, libra: 0.86,
      pal: { bg: [13, 12, 11], accent: [230, 220, 200], second: [190, 80, 70] }, motif: { dream: 0.4, motes: 0.4 },
      clues: ['La copertina blu, con l’etichetta.', 'Le aste, i cerchi, le lettere storte.', 'Un tema: “Da grande farò”.', 'Hai scritto una cosa che non hai fatto. E una che hai fatto senza accorgertene.', 'In fondo, a matita rossa: bravo.'],
      ora: 'Le pagine a quadretti, la gomma che ha bucato la carta in un punto.',
      allora: '' }),
    M('giocattolo', 'Il pupazzo senza un occhio', 'luogo', { hidden: true, terrain: 'legno', modus: 'pentatonico', hush: 0.92, peace: 60, lumina: 'soffuse',
      secret: { at: ['cassetto', 'soffitta', 'stanza'], chance: 0.25, linger: 50 },
      levels: { m_carillon: 0.3, m_respiro: 0.12, m_carezza: 0.15 }, set: { lumen: 0.35, velum: 0.5, oblio: 0.4 }, libra: 0.9,
      pal: { bg: [12, 11, 10], accent: [236, 214, 190], second: [170, 140, 120] }, motif: { dream: 0.5, cradle: 0.3, motes: 0.5 },
      ora: 'Un orsetto di pezza, spelacchiato, con un bottone al posto di un occhio. Lo prendi in mano: ha ancora l’odore del tuo letto.',
      allora: 'Gli raccontavi tutto. Non ha mai tradito nessun segreto.' }),
    M('spiaggia_foto', 'La fotografia sulla spiaggia', 'stato', { hidden: true, terrain: 'sabbia', modus: 'lidio', hush: 0.8, lumina: 'accese',
      secret: { at: ['spiaggia_inverno', 'mare', 'fotografie'], linger: 40 },
      levels: { m_mare: 0.35, m_gabbiani: 0.15, m_bambini: 0.12, m_vento: 0.15 }, set: { lumen: 0.4, nastro: 0.5, oblio: 0.5 }, libra: 0.85,
      pal: { bg: [13, 12, 10], accent: [240, 220, 180], second: [120, 170, 200] }, motif: { dream: 0.5, face: 0.4, sun: 0.4 },
      ora: 'Una fotografia con il bordo bianco smerlato: una spiaggia, un ombrellone a strisce, e un bambino in braccio a qualcuno che è tagliato fuori dall’inquadratura.',
      allora: 'Si vede solo una mano, sulla tua spalla. Hai passato la vita a chiederti di chi fosse.' }),
    M('canzone', 'La canzone di quell’estate', 'luogo', { hidden: true, terrain: 'legno', modus: 'ionio', hush: 0.6, lumina: 'soffuse',
      secret: { at: ['radio_notte', 'cassetto', 'estate', 'sala_proiezione'], chance: 0.3 },
      levels: { m_grammofono: 0.4, m_radio: 0.2, m_piano: 0.4, m_carillon: 0.25, m_cicale: 0.2 }, set: { lumen: 0.4, nastro: 0.55, velum: 0.4 }, libra: 0.8,
      pal: { bg: [13, 11, 9], accent: [250, 210, 150], second: [200, 120, 90] }, motif: { dream: 0.4, haze: 0.6, sun: 0.4 },
      newMelody: true,
      ora: 'Dalla radio esce una canzone. Le prime note, e sei di nuovo lì: l’estate, il caldo, le voci. La melodia è cambiata: adesso suona quella.',
      allora: 'Non ricordi il titolo, né chi la cantava. Ricordi solo come ti sentivi.' }),
    M('sala_ritorni', 'La sala dei ritorni', 'luogo', { terrain: 'pietra', modus: 'eolio', hush: 0.85, peace: 70, lumina: 'soffuse',
      levels: { m_passi: 0.15, m_canto: 0.12, m_pendolo: 0.2, m_vento: 0.1 }, set: { lumen: 0.3, velum: 0.5, crypta: 0.85, aether: 0.5 }, libra: 0.88,
      pal: DREAM, motif: { dream: 0.7, corridor: 0.3 },
      ora: 'Una sala d’aspetto grande come una stazione, con le panche di legno. Ogni tanto si apre una porta in fondo, e qualcuno entra. Non sai mai chi.',
      allora: 'Si aspetta senza fretta. Qui nessuno è in ritardo.' }),
    M('amico_perso', 'Un amico che non vedi più', 'stato', { hidden: true, terrain: 'ghiaia', modus: 'dorico', hush: 0.75, lumina: 'accese',
      secret: { at: ['sala_ritorni', 'parco_giochi', 'sala_giochi'], chance: 0.35, linger: 40 },
      levels: { m_bambini: 0.15, m_uccelli: 0.15, m_altalena: 0.15, m_voci: 0.12 }, set: { lumen: 0.4, nastro: 0.4, oblio: 0.4 }, libra: 0.82,
      pal: { bg: [12, 12, 11], accent: [230, 220, 196], second: [150, 160, 140] }, motif: { dream: 0.5, meet: 0.6 },
      clues: ['Eravate inseparabili.', 'Poi una città diversa, un lavoro, gli anni.', 'Non c’è stato un litigio. Solo silenzio.', 'Qui ti saluta come se vi foste visti ieri.', 'Ti chiede: ti ricordi quella volta? E tu sì, te la ricordi.'],
      ora: 'È seduto sul muretto dove vi trovavate sempre. Ha la stessa faccia di allora.',
      allora: '' }),
    M('nonno_orto', 'Il nonno nell’orto', 'stato', { hidden: true, terrain: 'erba', modus: 'lidio', hush: 0.85, peace: 70, lumina: 'accese',
      secret: { at: ['giorni_nonni', 'sala_ritorni', 'mano_nonno'], linger: 50, chance: 0.2, needs: ['mano_nonno'] },
      levels: { m_uccelli: 0.3, m_cicale: 0.2, m_vento: 0.15, m_carezza: 0.15 }, set: { lumen: 0.45, velum: 0.55, chorus: 0.2 }, libra: 0.88,
      pal: { bg: [12, 13, 10], accent: [236, 230, 180], second: [140, 170, 110] }, motif: { dream: 0.5, field: 0.5, sun: 0.4, hand: 0.4 },
      ora: 'Il nonno è nell’orto, con il cappello di paglia, chino sui pomodori. È in piedi, sta bene. Si raddrizza, si asciuga la fronte, ti fa cenno di venire.',
      allora: 'Non dice niente. Ti dà in mano un pomodoro caldo di sole. Tu sai che non è possibile, e lo mangi lo stesso.' }),
    M('massimo_partita', 'Una partita a due', 'stato', { hidden: true, terrain: 'legno', modus: 'ionio', hush: 0.6, lumina: 'spente',
      secret: { at: ['massimo', 'sala_giochi', 'sala_ritorni'], linger: 45, chance: 0.25 },
      levels: { m_arcade: 0.5, m_voci: 0.12, m_ronzio: 0.15 }, set: { lumen: 0.35, nastro: 0.3 }, libra: 0.75,
      pal: { bg: [7, 6, 11], accent: [140, 220, 255], second: [240, 120, 200] }, motif: { dream: 0.5, arcade: 0.7 },
      clues: ['Due joystick, uno schermo.', 'Lui prende sempre il personaggio rosso.', 'Ride quando sbagli. Tu ridi quando sbaglia lui.', 'Il punteggio sale. Nessuno dei due vuole smettere.', 'Ti dice: allora, com’è il nuovo gioco? E tu glielo racconti.'],
      ora: 'Una stanza al buio, la luce blu dello schermo sulle vostre facce. Siete seduti sul pavimento, spalla contro spalla.',
      allora: '' }),
    // ——————————————————————— LA TESTA
    M('fuori_posto', 'Fuori posto', 'stato', { terrain: 'pietra', modus: 'hirajoshi', hush: 0.4, lumina: 'soffuse', press: 50,
      levels: { m_voci: 0.2, m_acufene: 0.25, m_ronzio: 0.3, m_cuore: 0.2 }, set: { lumen: 0.2, mercurius: 0.6, distantia: 0.4 }, libra: 0.7,
      pal: { bg: [9, 10, 10], accent: [200, 214, 210], second: [100, 116, 112] }, motif: { doubt: 0.6, crowd: 0.3 },
      clues: ['Tutti sembrano sapere dove andare.', 'Tu sei entrato dalla porta sbagliata, in una vita sbagliata.', 'Le cose hanno i nomi giusti, ma non ti appartengono.', 'Ti chiedi come sei arrivato qui.'],
      ora: 'Un posto normale, gente normale. Solo tu sei del colore sbagliato, come una figurina incollata nell’album di un altro.',
      allora: '' }),
    M('impazzito', 'Sto impazzendo?', 'stato', { terrain: 'pietra', modus: 'hirajoshi', hush: 0.35, lumina: 'soffuse',
      levels: { m_sussurri: 0.4, m_acufene: 0.3, m_radio: 0.2, m_pendolo: 0.2 }, set: { lumen: 0.2, mercurius: 0.7, nastro: 0.4, tempestas: 0.3 }, libra: 0.62,
      pal: { bg: [8, 8, 9], accent: [210, 206, 220], second: [100, 96, 120] }, motif: { doubt: 0.8, whispers: 0.6, cracks: 0.3 },
      clues: ['Hai chiuso la porta? Torni a controllare.', 'Hai chiuso la porta? Torni a controllare.', 'Le parole di una frase si staccano dal loro significato.', 'Ti senti guardare da dentro.', 'Chi è che pensa questi pensieri?', 'Ti sembra di impazzire. Non stai impazzendo: sei stanco, e hai paura.'],
      ora: 'I pensieri girano troppo veloci, come una radio che salta tra le stazioni. Ti domandi se sia normale. Te lo domandi ancora.',
      allora: '' }),
    M('sbagliato_tutto', 'Ho sbagliato tutto', 'stato', { terrain: 'pietra', modus: 'eolio', hush: 0.6, lumina: 'soffuse',
      levels: { m_pioggia: 0.3, m_pendolo: 0.3, m_respiro: 0.15, m_vento: 0.15 }, set: { lumen: 0.2, distantia: 0.5, nastro: 0.3 }, libra: 0.78,
      pal: { bg: [8, 9, 10], accent: [196, 204, 216], second: [90, 100, 116] }, motif: { tears: 0.4, rainfall: 0.4 },
      clues: ['La scuola. Il lavoro. Quella persona.', 'Le parole che hai detto. Quelle che non hai detto.', 'Tutto, ti sembra. Tutto sbagliato.', 'Poi, piano: non tutto.', 'C’è un figlio che ride. C’è qualcuno che ti aspetta a casa.', 'Questi non sono errori.'],
      ora: 'La pioggia sul vetro e la lista che la testa scrive da sola, sempre più lunga, di ogni cosa che avresti dovuto fare diversamente.',
      allora: '' }),
    M('pensieri_neri', 'I pensieri che passano', 'stato', { terrain: 'nuvola', modus: 'eolio', hush: 0.75, peace: 90, lumina: 'soffuse',
      levels: { m_vento: 0.3, m_tuono: 0.12, m_pioggia: 0.2, m_respiro: 0.2, m_carezza: 0.1 }, set: { lumen: 0.25, velum: 0.4, distantia: 0.5 }, libra: 0.85,
      pal: { bg: [7, 7, 9], accent: [200, 206, 226], second: [96, 104, 130] }, motif: { void: 0.4, haze: 0.5, purify: 0.2 },
      clues: ['A volte la testa dice cose terribili.', 'Che sarebbe meglio sparire. Che sarebbe meglio non esserci.', 'Un pensiero non è un fatto.', 'Lo puoi guardare passare, come un temporale dietro il vetro.', 'Non devi obbedirgli.', 'Se lo dici ad alta voce a qualcuno, diventa più piccolo.', 'Il temporale passa. Tu resti.'],
      ora: 'Nuvole nere che attraversano la testa senza chiedere permesso. Fanno rumore, fanno paura. Tu le guardi dalla finestra, al riparo.',
      allora: 'Pensare non è fare. E se questi pensieri tornano troppo spesso, parlane con qualcuno: un amico, un medico. Non sei l’unico, e non sei solo.' })
  ];
  NEW.forEach(p => { if (!ATH.PLACE[p.id]) { ATH.PLACES.push(p); ATH.PLACE[p.id] = p; } });

  // altri luoghi misteriosi diventano nascosti: bisogna fermarsi nel posto giusto
  ['porta_bosco', 'casa_luce', 'campana_sola', 'orologio_fermo', 'stanza_specchi', 'binario_morto', 'grotta'].forEach(id => { if (ATH.PLACE[id]) ATH.PLACE[id].hidden = true; });
  ATH.LINGER_EXTRA = { porta_bosco: 35, casa_luce: 40, campana_sola: 45, orologio_fermo: 40, stanza_specchi: 35, binario_morto: 30, grotta: 40 };
})(window.ATH);
