/* ATHANOR — IL CUORE E I POSTI DI PASSAGGIO. Gli stati d'animo che non hanno
   un luogo, e i posti dove si passa senza fermarsi.
   un luogo moderatamente sicuro */
window.ATH = window.ATH || {};

(function (ATH) {
  const N = (id, name, kind, level, o) => Object.assign({ id, name, kind, level, exits: [], motif: {} }, o);
  const NEW = [
    // ——————————————————————— IL CUORE
    N('domenica_sera', 'La domenica sera', 'stato', 0, { terrain: 'legno', modus: 'eolio', hush: 0.7, lumina: 'soffuse',
      levels: { m_radio: 0.15, m_stoviglie: 0.15, m_pendolo: 0.25, m_campane: 0.08, m_motore: 0.05 }, set: { lumen: 0.3, velum: 0.4, nastro: 0.3 }, libra: 0.82,
      pal: { bg: [10, 9, 10], accent: [214, 200, 210], second: [120, 100, 120] }, motif: { windows: 0.5, haze: 0.4 },
      ora: 'La luce che cala presto, la sigla di un programma alla televisione, lo zaino da preparare per domani. Una tristezza leggera, senza un motivo preciso.',
      allora: 'Da bambino la domenica sera aveva un sapore tutto suo. Ce l’ha ancora.' }),
    N('nostalgia', 'La nostalgia', 'stato', 0, { terrain: 'nuvola', modus: 'lidio', hush: 0.8, lumina: 'soffuse',
      levels: { m_grammofono: 0.2, m_carillon: 0.2, m_fruscio: 0.2, m_vento: 0.1 }, set: { lumen: 0.35, velum: 0.5, nastro: 0.5, oblio: 0.4 }, libra: 0.86,
      pal: { bg: [12, 10, 9], accent: [236, 210, 170], second: [160, 120, 100] }, motif: { haze: 0.6, motes: 0.5 },
      ora: 'Un dolore dolce, che non vorresti mandare via. Ti manca una cosa che c’è stata, e una che forse non c’è mai stata.',
      allora: 'Nostalgia vuol dire “il dolore del ritorno”. Si torna, ma non si arriva mai.' }),
    N('rimpianto', 'Il rimpianto', 'stato', 0, { terrain: 'pietra', modus: 'eolio', hush: 0.75, lumina: 'soffuse',
      levels: { m_pioggia: 0.2, m_pendolo: 0.3, m_treno: 0.15 }, set: { lumen: 0.25, distantia: 0.5 }, libra: 0.82,
      pal: { bg: [9, 9, 10], accent: [200, 200, 214], second: [100, 100, 120] }, motif: { train: 0.3, rainfall: 0.3 },
      ora: 'Una porta che hai lasciato chiudere. Ci passi davanti ogni tanto, e ti chiedi cosa ci fosse dall’altra parte.',
      allora: '' }),
    N('vergogna', 'La vergogna', 'stato', 0, { terrain: 'pietra', modus: 'hirajoshi', hush: 0.5, lumina: 'accese', press: 30,
      levels: { m_voci: 0.2, m_cuore: 0.3, m_acufene: 0.15 }, set: { lumen: 0.2, distantia: 0.3 }, libra: 0.72,
      pal: { bg: [12, 9, 9], accent: [236, 180, 170], second: [160, 90, 90] }, motif: { crowd: 0.3, fever: 0.4 },
      clues: ['Il calore che sale sulla faccia.', 'Vorresti sparire sotto il pavimento.', 'Ti torna in mente anni dopo, all’improvviso, mentre lavi i piatti.', 'Nessun altro se lo ricorda.'],
      ora: 'Le guance che bruciano, lo sguardo basso. Una cosa piccola, che dentro diventa enorme.',
      allora: '' }),
    N('paura_perdere', 'La paura di perdere qualcuno', 'stato', 0, { terrain: 'legno', modus: 'eolio', hush: 0.7, lumina: 'spente',
      levels: { m_cuore: 0.3, m_respiro: 0.25, m_pendolo: 0.2, m_telefono: 0.1 }, set: { lumen: 0.25, distantia: 0.4 }, libra: 0.8, bpm: 0.55,
      pal: { bg: [7, 7, 9], accent: [206, 206, 226], second: [96, 100, 130] }, motif: { ceiling: 0.5 },
      clues: ['Il telefono squilla a un’ora strana.', 'Il cuore salta un colpo prima ancora di rispondere.', 'Non era niente.', 'Ma per un secondo hai visto il mondo senza di lui.', 'Vai a guardare tuo figlio che dorme.'],
      ora: 'Di notte, quando tutti dormono, la paura arriva da sola: che un giorno qualcuno che ami non ci sia più.',
      allora: '' }),
    N('gratitudine', 'La gratitudine', 'stato', 0, { terrain: 'erba', modus: 'lidio', hush: 0.75, peace: 60, lumina: 'accese',
      levels: { m_uccelli: 0.3, m_carezza: 0.2, m_campane: 0.1 }, set: { lumen: 0.45, velum: 0.55, chorus: 0.25 }, libra: 0.88,
      pal: { bg: [13, 12, 10], accent: [250, 230, 190], second: [200, 170, 130] }, motif: { sun: 0.5, haze: 0.4 },
      ora: 'Un momento qualunque, e all’improvviso ti accorgi di tutto quello che hai. Ti viene da dire grazie, e non sai bene a chi.',
      allora: 'Ai nonni, forse. A chi c’è stato. A chi c’è ancora.' }),
    N('tenerezza', 'La tenerezza', 'stato', 0, { terrain: 'nuvola', modus: 'pentatonico', hush: 0.85, peace: 50, lumina: 'soffuse',
      levels: { m_carillon: 0.25, m_respiro: 0.15, m_carezza: 0.25 }, set: { lumen: 0.4, velum: 0.6, chorus: 0.3 }, libra: 0.9,
      pal: { bg: [13, 11, 11], accent: [255, 220, 210], second: [200, 160, 170] }, motif: { cradle: 0.4, haze: 0.5 },
      ora: 'Una mano piccola nella tua. Una persona anziana che si sistema il cappello. Un cane che sogna e muove le zampe. Il cuore che si scioglie un poco.',
      allora: '' }),
    N('stupore', 'Lo stupore', 'stato', 0, { terrain: 'erba', modus: 'armonici', hush: 0.7, lumina: 'spente',
      levels: { m_grilli: 0.3, m_vento: 0.15, m_carezza: 0.2 }, set: { lumen: 0.45, aether: 0.8, chorus: 0.3 }, libra: 0.88,
      pal: { bg: [4, 5, 10], accent: [220, 226, 255], second: [140, 120, 220] }, motif: { stars: 1, nebula: 0.4, fireflies: 0.3 },
      ora: 'La bocca aperta davanti a qualcosa di troppo grande: il cielo di agosto senza luna, una tempesta sul mare, tuo figlio appena nato.',
      allora: 'Da bambino succedeva ogni giorno. Adesso è raro, e per questo vale di più.' }),
    N('sollievo', 'Il sollievo', 'stato', 0, { terrain: 'erba', modus: 'ionio', hush: 0.7, peace: 50, lumina: 'accese',
      levels: { m_respiro: 0.3, m_uccelli: 0.25, m_vento: 0.15 }, set: { lumen: 0.45, velum: 0.5 }, libra: 0.86,
      pal: { bg: [12, 13, 12], accent: [230, 240, 220], second: [160, 190, 160] }, motif: { sun: 0.4, purify: 0.3 },
      ora: 'Il medico che sorride. La telefonata che dice: è tutto a posto. Le gambe che tremano dopo, quando non serve più.',
      allora: '' }),
    N('calma_dopo', 'La calma dopo la tempesta', 'stato', 0, { terrain: 'erba', modus: 'pentatonico', hush: 0.75, peace: 60, lumina: 'soffuse',
      levels: { m_goccia: 0.35, m_uccelli: 0.2, m_vento: 0.1, m_tuono: 0.05 }, set: { lumen: 0.4, velum: 0.5, aether: 0.5 }, libra: 0.88,
      pal: { bg: [10, 12, 12], accent: [214, 236, 236], second: [130, 170, 170] }, motif: { rainfall: 0.3, sun: 0.3, haze: 0.4 },
      ora: 'Le gocce che cadono ancora dalle grondaie, l’aria lavata, un tuono lontanissimo che se ne va. Tutto è bagnato, e tutto è nuovo.',
      allora: '' }),
    // ——————————————————————— I POSTI DI PASSAGGIO
    N('autogrill', 'L’autogrill di notte', 'luogo', 0, { terrain: 'pietra', modus: 'dorico', hush: 0.4, lumina: 'accese',
      levels: { m_motore: 0.4, m_ronzio: 0.3, m_voci: 0.1, m_radio: 0.1 }, set: { lumen: 0.25, distantia: 0.5 }, libra: 0.7,
      pal: { bg: [9, 10, 11], accent: [220, 226, 236], second: [120, 140, 170] }, motif: { lights: 0.6, path: 0.3 },
      ora: 'Le luci bianche nel buio dell’autostrada, un caffè al bancone, camionisti che non parlano. Tutti stanno andando da qualche parte, nessuno resta.',
      allora: 'Ti fermavi qui nei viaggi lunghi, da bambino, mezzo addormentato. Ti compravano le caramelle alla menta.' }),
    N('lavanderia', 'La lavanderia a gettoni', 'luogo', 0, { terrain: 'pietra', modus: 'insen', hush: 0.6, lumina: 'accese',
      levels: { m_ronzio: 0.4, m_macchine: 0.12, m_goccia: 0.1, m_radio: 0.06 }, set: { lumen: 0.2, nastro: 0.2 }, libra: 0.78,
      pal: { bg: [10, 11, 11], accent: [210, 230, 226], second: [110, 140, 136] }, motif: { lights: 0.4, corridor: 0.3 },
      ora: 'Le due di notte, le lavatrici che girano tutte insieme, il neon. Una sedia di plastica, una rivista vecchia. Guardi i panni che ruotano e non pensi a niente.',
      allora: '' }),
    N('edicola', 'L’edicola delle figurine', 'luogo', 0, { terrain: 'pietra', modus: 'ionio', hush: 0.45, lumina: 'accese',
      levels: { m_voci: 0.12, m_bambini: 0.15, m_passi: 0.15, m_fruscio: 0.2, m_motore: 0.06 }, set: { lumen: 0.35, nastro: 0.4, oblio: 0.35 }, libra: 0.75,
      pal: { bg: [12, 11, 10], accent: [240, 214, 170], second: [190, 100, 80] }, motif: { haze: 0.3, windows: 0.3 },
      ora: 'Il chiosco verde all’angolo, i giornali appesi con le mollette, i bustini delle figurine. Ne apri uno con le mani che tremano: doppia, doppia, doppia, e poi quella che mancava.',
      allora: 'L’album non l’hai mai finito. Da qualche parte manca ancora una figurina.' }),
    N('cinema_paese', 'Il cinema del paese', 'luogo', 0, { terrain: 'legno', modus: 'lidio', hush: 0.6, lumina: 'spente',
      levels: { m_proiettore: 0.35, m_voci: 0.1, m_fruscio: 0.15, m_grammofono: 0.08 }, set: { lumen: 0.3, nastro: 0.5, oblio: 0.4 }, libra: 0.8,
      pal: { bg: [7, 6, 7], accent: [240, 220, 190], second: [170, 60, 60] }, motif: { beam: 0.8, film: 0.4 },
      ora: 'Le poltrone di velluto rosso che cigolano, il fascio di luce pieno di fumo, il film del sabato pomeriggio. La sala si zittisce quando si spengono le luci.',
      allora: 'Adesso è un supermercato. Ma se chiudi gli occhi senti ancora le poltrone che si richiudono da sole.' }),
    N('tuffi', 'Il fiume d’estate', 'luogo', 0, { terrain: 'acqua', modus: 'ionio', hush: 0.4, lumina: 'accese',
      levels: { m_ruscello: 0.5, m_bambini: 0.3, m_cicale: 0.4, m_uccelli: 0.15 }, set: { lumen: 0.4, velum: 0.4 }, libra: 0.72,
      pal: { bg: [12, 13, 10], accent: [230, 236, 190], second: [120, 170, 150] }, motif: { river: 0.7, sun: 0.5 },
      ora: 'L’acqua gelata anche ad agosto, i sassi caldi su cui stendersi ad asciugare, il salto dalla roccia alta che fanno solo i più grandi.',
      allora: 'Un giorno l’hai fatto anche tu. Hai chiuso gli occhi e ti sei buttato. Non hai mai più avuto così tanto coraggio.' })
  ];
  NEW.forEach(p => { if (!ATH.PLACE[p.id]) { ATH.PLACES.push(p); ATH.PLACE[p.id] = p; } });
})(window.ATH);
