/* ATHANOR — CIÒ CHE È SUCCESSO E CIÒ CHE FORSE NO. Giorgio, la prima volta
   che hai visto la morte. Il Natale di quando eri bambino, e quello negli occhi
   di tuo figlio. La casa al mare d'inverno, le persiane. L'uovo della bisnonna.
   Dormire a finestra aperta, il sole che ti sveglia. La casa lasciata di
   fretta, e quella distrutta dai vandali. Lo spartito, preso e riportato. La
   seduta spiritica. E il nascondiglio, dove andare quando non si vuole più
   girare. Poi le cose che la mente si inventa da sola.
   un luogo moderatamente sicuro */
window.ATH = window.ATH || {};

(function (ATH) {
  const N = (id, name, kind, level, o) => Object.assign({ id, name, kind, level, exits: [], motif: {} }, o);
  const DREAM = { bg: [10, 9, 12], accent: [226, 214, 236], second: [150, 130, 170] };
  const NEW = [
    // ——————————————————————— LA CASA AL MARE
    N('casa_mare_inverno', 'La casa al mare d’inverno', 'luogo', 0, { terrain: 'legno', modus: 'eolio', hush: 0.6, lumina: 'soffuse',
      levels: { m_mare: 0.4, m_vento: 0.45, m_scricchiolio: 0.25, m_tubature: 0.12, m_gabbiani: 0.06 }, set: { lumen: 0.3, crypta: 0.6, distantia: 0.5 }, libra: 0.75,
      pal: { bg: [9, 10, 12], accent: [206, 214, 222], second: [100, 116, 130] }, motif: { haze: 0.5, windows: 0.4 },
      clues: ['Il paese è vuoto, le serrande sono tutte abbassate.', 'La casa ha preso umido. C’è odore di chiuso e di sale.', 'Una cosa da aggiustare, poi un’altra, poi un’altra ancora.', 'Nessuno a cui chiedere una mano.', 'La sera mangi in piedi in cucina, ascoltando il mare che non si vede.'],
      ora: 'La casa al mare fuori stagione. Il mare grigio, il vento che fischia negli spifferi, i mobili coperti dai teli. Sei venuto da solo a sistemare le cose.',
      allora: '' }),
    N('persiane', 'Le persiane da smontare', 'stato', 0, { terrain: 'legno', modus: 'dorico', hush: 0.35, lumina: 'accese',
      levels: { m_scricchiolio: 0.45, m_vento: 0.4, m_mare: 0.25, m_passi: 0.15 }, set: { lumen: 0.25, calcinatio: 0.25 }, libra: 0.58,
      pal: { bg: [11, 11, 11], accent: [214, 206, 190], second: [130, 120, 100] }, motif: { windows: 0.6, ruin: 0.3 },
      clues: ['Le cerniere arrugginite non vogliono saperne.', 'La carta vetrata, la vernice vecchia che si sbriciola.', 'Le dita fredde, il cacciavite che scivola.', 'Non volevi farlo. Proprio no.', 'Lo hai fatto lo stesso, una persiana alla volta.', 'Nessuno lo saprà mai. Tu sì.'],
      ora: 'Le persiane staccate e appoggiate al muro, una fila di legno scrostato. Il vento del mare che porta via la polvere della carta vetrata.',
      allora: '' }),
    N('notte_finestra', 'Dormire a finestra aperta', 'stato', 0, { terrain: 'legno', modus: 'pentatonico', hush: 0.85, peace: 70, lumina: 'spente',
      levels: { m_grilli: 0.4, m_vento: 0.2, m_cani: 0.06, m_campane: 0.05, m_respiro: 0.15, m_foglie: 0.15 }, set: { lumen: 0.35, velum: 0.5, aether: 0.5 }, libra: 0.9,
      pal: { bg: [5, 6, 9], accent: [200, 210, 236], second: [90, 100, 140] }, motif: { stars: 0.5, haze: 0.4 },
      ora: 'D’estate, la finestra spalancata, la tenda che si gonfia piano. Fuori i grilli e il fresco della notte che entra fino al letto.',
      allora: 'Dormivi così, da ragazzo, sopra le lenzuola. Il mondo intero entrava dalla finestra, e non faceva paura.' }),
    N('sole_sveglia', 'Il sole che ti sveglia', 'stato', 0, { terrain: 'legno', modus: 'lidio', hush: 0.7, peace: 60, lumina: 'accese',
      levels: { m_uccelli: 0.45, m_cicale: 0.2, m_voci: 0.06, m_campane: 0.08 }, set: { lumen: 0.5, velum: 0.6, chorus: 0.25 }, libra: 0.85,
      pal: { bg: [16, 14, 10], accent: [255, 236, 190], second: [230, 180, 120] }, motif: { sun: 1, beam: 0.8, motes: 0.6 },
      ora: 'Il sole del mattino ti batte addosso dalla finestra rimasta aperta, caldo, bianco, insistente. Gli occhi chiusi diventano rossi.',
      allora: 'Era il suo modo di dirti: alzati, c’è una giornata intera là fuori. E tu restavi ancora un po’, solo per sentirlo.' }),
    // ——————————————————————— LE FESTE DI UNA VOLTA
    N('natale_bambino', 'Il Natale di quando eri bambino', 'luogo', 0, { terrain: 'legno', modus: 'ionio', hush: 0.5, peace: 80, lumina: 'candele',
      levels: { m_campane: 0.3, m_carillon: 0.35, m_camino: 0.35, m_voci: 0.15, m_stoviglie: 0.12, m_bambini: 0.08 }, set: { lumen: 0.45, velum: 0.55, chorus: 0.3 }, libra: 0.82,
      pal: { bg: [12, 9, 8], accent: [255, 214, 150], second: [190, 60, 50] }, motif: { xmas: 1, snow: 0.4, candles: 0.4 },
      ora: 'Le lucine dell’albero che si accendono e si spengono, il presepe col muschio vero, l’odore di mandarini e di brodo. Fuori fa freddo, dentro è tutto caldo.',
      allora: 'Il Natale si sentiva. Era nell’aria giorni prima, si poteva quasi toccare. Non sai dove sia finito.' }),
    N('letterina', 'La letterina', 'stato', 0, { terrain: 'legno', modus: 'lidio', hush: 0.7, peace: 70, lumina: 'candele',
      levels: { m_carillon: 0.3, m_fruscio: 0.25, m_bambini: 0.12, m_camino: 0.2, m_carezza: 0.15 }, set: { lumen: 0.45, velum: 0.55 }, libra: 0.86,
      pal: { bg: [13, 10, 9], accent: [255, 220, 170], second: [190, 90, 80] }, motif: { xmas: 0.7, motes: 0.5 },
      clues: ['Tuo figlio scrive con la lingua tra i denti.', 'Le lettere storte, una parola cancellata tre volte.', 'Ti chiede come si scrive “renna”.', 'La mattina di Natale strappa la carta, e il mondo si ferma.', 'Lo guardi, e il Natale è di nuovo lì: nei suoi occhi.'],
      ora: 'Un foglio a righe, i pennarelli, la busta da incollare. Una lista di desideri scritta con la serietà di un trattato.',
      allora: '' }),
    N('uovo_pasqua', 'L’uovo della bisnonna', 'luogo', 0, { terrain: 'legno', modus: 'pentatonico', hush: 0.85, peace: 70, lumina: 'soffuse',
      levels: { m_fruscio: 0.3, m_pendolo: 0.2, m_voci: 0.1, m_campane: 0.12, m_carillon: 0.15 }, set: { lumen: 0.45, velum: 0.5, oblio: 0.35, nastro: 0.3 }, libra: 0.88,
      pal: { bg: [14, 12, 10], accent: [255, 214, 170], second: [200, 120, 160] }, motif: { egg: 1, motes: 0.5 },
      clues: ['Avevi due anni, forse meno.', 'La bisnonna entra con un uovo di Pasqua enorme, più grande di te.', 'La carta lucida che fruscia, il fiocco viola.', 'Ricordi la stanza, le luci, l’odore della cera e della naftalina.', 'Era grande perché tu eri piccolo. Lo è ancora.'],
      ora: 'Una stanza con le tende di pizzo e la luce gialla del pomeriggio. Al centro, un uovo di carta argentata che arriva quasi al soffitto.',
      allora: '' }),
    N('giorni_uguali', 'I giorni tutti uguali', 'stato', 0, { terrain: 'pietra', modus: 'dorico', hush: 0.5, lumina: 'accese',
      levels: { m_pendolo: 0.35, m_ronzio: 0.3, m_motore: 0.1, m_telefono: 0.1 }, set: { lumen: 0.2, nastro: 0.2, oblio: 0.4 }, libra: 0.72,
      pal: { bg: [11, 11, 11], accent: [200, 200, 200], second: [120, 120, 120] }, motif: { corridor: 0.3, lights: 0.2 },
      clues: ['Lunedì, martedì, mercoledì.', 'Il caffè, la macchina, il lavoro, la cena.', 'Ti accorgi che è dicembre perché lo dice il calendario.', 'Le lucine nei negozi già da ottobre.', 'Dove è finita quella cosa che si sentiva nell’aria?'],
      ora: 'Le settimane che scivolano una sull’altra, tutte dello stesso grigio. Le feste arrivano come una data, non più come un profumo.',
      allora: '' }),
    // ——————————————————————— GIORGIO
    N('giorgio_moto', 'La moto per terra', 'stato', 0, { terrain: 'pietra', modus: 'eolio', hush: 0.55, lumina: 'soffuse', candles: true,
      levels: { m_motore: 0.3, m_voci: 0.15, m_vento: 0.25, m_cuore: 0.25 }, set: { lumen: 0.25, distantia: 0.5, nastro: 0.3 }, libra: 0.75, bpm: 0.6,
      pal: { bg: [8, 9, 11], accent: [200, 210, 230], second: [70, 100, 160] }, motif: { siren: 0.6, path: 0.4 },
      clues: ['L’autobus rallenta.', 'A bordo strada, una moto sdraiata sull’asfalto.', 'La riconosci. Il colore, il casco.', 'Nessuno parla, nell’autobus.', 'Hai capito che era lui. Giorgio.', 'È stata la prima volta che hai visto la morte da vicino.'],
      ora: 'Dal finestrino dell’autobus, una curva, delle luci blu che girano senza suono, persone ferme a bordo strada.',
      allora: 'Accendi un lumino per Giorgio, se vuoi.' }),
    N('obitorio', 'L’obitorio', 'luogo', 0, { terrain: 'pietra', modus: 'insen', hush: 0.92, lumina: 'accese',
      levels: { m_ronzio: 0.3, m_goccia: 0.12, m_passi: 0.1, m_respiro: 0.12 }, set: { lumen: 0.2, distantia: 0.4, crypta: 0.85 }, libra: 0.9,
      pal: { bg: [10, 11, 12], accent: [214, 226, 236], second: [110, 126, 140] }, motif: { corridor: 0.4, veil: 0.6 },
      clues: ['Una stanza bianca e fredda.', 'Il ronzio delle luci al neon.', 'Lui è lì, sul tavolo, sotto un lenzuolo.', 'Gli tocchi la mano. È fredda come il marmo.', 'Non è più lui. Ed è ancora lui.', 'Esci, e fuori il sole sembra un’offesa.'],
      ora: 'Un corridoio, una porta, il freddo che si sente sulla pelle. Avevi la sua età. Non sapevi che si potesse morire così presto.',
      allora: '' }),
    // ——————————————————————— LA CASA LASCIATA DI FRETTA
    N('casa_fretta', 'La casa lasciata di fretta', 'luogo', 0, { terrain: 'legno', modus: 'eolio', hush: 0.8, lumina: 'soffuse',
      levels: { m_pendolo: 0.0, m_vento: 0.25, m_scricchiolio: 0.25, m_goccia: 0.12, m_fruscio: 0.15 }, set: { lumen: 0.25, oblio: 0.5, distantia: 0.6 }, libra: 0.85,
      pal: { bg: [10, 9, 8], accent: [220, 200, 170], second: [120, 100, 84] }, motif: { clutter: 0.4, motes: 0.7, wallpaper: 0.4 },
      clues: ['I piatti ancora sul tavolo, con le forchette posate di traverso.', 'Un cappotto sulla sedia.', 'Il calendario fermo a un mese di tanti anni fa.', 'Una bambola sul letto, girata verso la porta.', 'Se ne sono andati in un giorno, e non sono più tornati.'],
      ora: 'Tutto è rimasto come quel giorno: le tazze nella credenza, le lettere sul mobile dell’ingresso, le scarpe sotto il letto. Solo la polvere si è mossa.',
      allora: 'Avrebbero dovuto lasciarla così. È un museo di una vita qualunque, e per questo preziosissimo.' }),
    N('casa_vandali', 'La casa distrutta', 'luogo', 0, { terrain: 'pietra', modus: 'hirajoshi', hush: 0.45, lumina: 'soffuse',
      levels: { m_vento: 0.45, m_goccia: 0.25, m_scricchiolio: 0.3, m_cani: 0.06 }, set: { lumen: 0.2, distantia: 0.6, crypta: 0.75 }, libra: 0.7,
      pal: { bg: [9, 8, 8], accent: [200, 186, 170], second: [110, 90, 84] }, motif: { ruin: 1, cracks: 0.5 },
      ora: 'Negli anni è entrata gente. Hanno rotto i vetri, rovesciato i cassetti, scritto sui muri, portato via quello che si poteva vendere. Le fotografie calpestate.',
      allora: 'Una casa abbandonata non è vuota: è piena di qualcuno che non c’è. Nessuno ha avuto rispetto per lui.' }),
    N('spartito', 'Lo spartito', 'luogo', 0, { terrain: 'legno', modus: 'ionio', hush: 0.85, lumina: 'soffuse',
      levels: { m_piano: 0.45, m_carillon: 0.25, m_fruscio: 0.2, m_pendolo: 0.1 }, set: { lumen: 0.35, oblio: 0.45, nastro: 0.45 }, libra: 0.86,
      pal: { bg: [12, 10, 9], accent: [236, 216, 180], second: [140, 110, 90] }, motif: { motes: 0.6, film: 0.15 },
      newMelody: true,
      ask: [
        { q: 'Sul leggio di un pianoforte sfondato c’è uno spartito dell’Ottocento, per bambini. Lo prendi?', ifnot: 'spartito_preso', a: [
          { t: 'Lo prendo', f: 'spartito_preso', say: 'Lo pieghi in quattro e lo metti nella giacca. Ti sembra di sentire una porta che si chiude, di sopra.' },
          { t: 'Lo lascio', f: 'spartito_lasciato', say: 'Lo lasci aperto alla stessa pagina. Qualcuno, una volta, ci ha imparato a suonare.', mus: { velum: 0.04 } },
          { t: 'Lo suono', say: 'Sul pianoforte scordato escono poche note. Ma sono le sue.', mus: { m_piano: 0.04 } }] },
        { q: 'Sono passati anni. Lo spartito è ancora nella tua giacca. Lo rimetti dove l’hai trovato?', if: 'spartito_preso', ifnot: 'spartito_riportato', a: [
          { t: 'Sì, lo riporto', f: 'spartito_riportato', say: 'Lo rimetti sul leggio, aperto alla stessa pagina. Il bambino che abitava qui, forse, se ne accorge.', mus: { velum: 0.06, m_carillon: 0.04 } },
          { t: 'Non ancora', say: 'Lo terrai ancora un po’. Pesa più di un foglio.' }] }
      ],
      ora: 'Un pianoforte con i tasti ingialliti, metà muti. Sul leggio, un fascicolo di musica con una copertina disegnata a mano: valzerini, filastrocche, esercizi per piccole dita.',
      allora: 'Lo spartito apparteneva a un bambino di centocinquant’anni fa. Il nome è scritto a matita, in un angolo.' }),
    N('seduta', 'La seduta spiritica', 'stato', 0, { terrain: 'legno', modus: 'hirajoshi', hush: 0.75, lumina: 'candele',
      levels: { m_candele: 0.3, m_sussurri: 0.3, m_pendolo: 0.2, m_respiro: 0.2, m_vento: 0.12 }, set: { lumen: 0.2, distantia: 0.5, mercurius: 0.5 }, libra: 0.82, bpm: 0.6,
      pal: { bg: [7, 6, 6], accent: [230, 190, 140], second: [130, 70, 50] }, motif: { board: 1, candles: 0.6 },
      clues: ['Un foglio con le lettere scritte a cerchio, il sì e il no negli angoli.', 'Un dito ciascuno sulla monetina.', 'Chi la sta spingendo? Nessuno. Giurate.', 'Qualcuno chiede di parlare con il diavolo. Ridete troppo forte.', 'La monetina si ferma. Una candela si spegne da sola.', 'Forse avete scherzato con il fuoco. Forse no. Non l’avete più rifatto.'],
      ora: 'Da ragazzini, al buio, intorno a un tavolo. Le candele, le risate nervose, la monetina che comincia a muoversi piano sotto le dita.',
      allora: '' }),
    // ——————————————————————— L'IMMAGINATO
    N('teatro_vuoto', 'Il teatro dei ricordi', 'luogo', 0, { mind: true, terrain: 'legno', modus: 'armonici', hush: 0.8, lumina: 'soffuse',
      levels: { m_proiettore: 0.12, m_fruscio: 0.2, m_carillon: 0.12, m_vento: 0.1 }, set: { lumen: 0.35, velum: 0.5, aether: 0.5 }, libra: 0.88,
      pal: DREAM, motif: { dream: 0.6, beam: 0.6 },
      ora: 'Un teatro vuoto, il velluto rosso consumato. Sul palco, in silenzio, qualcuno recita una scena della tua vita. Non sai se è andata davvero così.',
      allora: 'Qui non c’è differenza tra quello che è successo e quello che ti sei raccontato. Tutto può essere vero, tutto può non esserlo.' }),
    N('corridoio_compleanni', 'Il corridoio dei compleanni', 'luogo', 0, { mind: true, terrain: 'legno', modus: 'lidio', hush: 0.75, lumina: 'candele',
      levels: { m_festa: 0.15, m_carillon: 0.25, m_bambini: 0.12, m_candele: 0.2 }, set: { lumen: 0.35, oblio: 0.5, nastro: 0.5 }, libra: 0.85,
      pal: DREAM, motif: { dream: 0.6, corridor: 0.7, candles: 0.4 },
      ora: 'Un corridoio lunghissimo, e dietro ogni porta un tuo compleanno: le candeline, le facce intorno al tavolo, i regali. Più vai avanti, più le porte sono piccole.',
      allora: 'Una porta è chiusa a chiave. Non ricordi quale compleanno ci sia dietro.' }),
    N('pioggia_casa', 'La pioggia dentro casa', 'luogo', 0, { mind: true, terrain: 'acqua', modus: 'eolio', hush: 0.6, lumina: 'soffuse',
      levels: { m_pioggia: 0.55, m_goccia: 0.35, m_pendolo: 0.15 }, set: { lumen: 0.3, oblio: 0.4 }, libra: 0.8,
      pal: DREAM, motif: { dream: 0.5, rainfall: 0.8, wallpaper: 0.3 },
      ora: 'Piove in salotto. Piano, senza fare danni. Le gocce cadono dal soffitto sul divano, sul tappeto, sul tavolo apparecchiato. Nessuno se ne preoccupa.',
      allora: 'Nel sogno sembrava normale. Solo da sveglio ti è venuta in mente la parola “tristezza”.' }),
    N('ascensore', 'L’ascensore che non si ferma', 'stato', 0, { mind: true, terrain: 'pietra', modus: 'hirajoshi', hush: 0.5, lumina: 'accese',
      levels: { m_ronzio: 0.4, m_macchine: 0.12, m_cuore: 0.2, m_campane: 0.05 }, set: { lumen: 0.2, distantia: 0.4 }, libra: 0.72, bpm: 0.55,
      pal: { bg: [10, 10, 11], accent: [214, 210, 200], second: [120, 116, 110] }, motif: { dream: 0.4, stairs: 0.5 },
      clues: ['Premi il tuo piano.', 'L’ascensore sale. Il tuo piano passa.', 'Premi ancora. Passa di nuovo.', 'I numeri sui bottoni non sono più numeri.', 'Le porte si aprono su un corridoio che conosci, ma non è casa tua.'],
      ora: 'Una cabina di specchi e moquette, un neon che ronza, una musica di attesa lontanissima.',
      allora: '' }),
    N('stanza_rovescia', 'La stanza al contrario', 'luogo', 0, { mind: true, terrain: 'legno', modus: 'insen', hush: 0.8, lumina: 'soffuse',
      levels: { m_pendolo: 0.25, m_fruscio: 0.15, m_carezza: 0.12 }, set: { lumen: 0.3, mercurius: 0.6, nastro: 0.4 }, libra: 0.85,
      pal: DREAM, motif: { dream: 0.6, cityFlip: 0.5, doubt: 0.3 },
      ora: 'La tua cameretta, identica, ma al contrario: il letto a destra invece che a sinistra, le scritte sui libri da leggere allo specchio, l’orologio che va all’indietro.',
      allora: 'Ti chiedi quale sia quella vera. Forse questa.' }),
    N('paese_bambini', 'Il paese dove tutti sono bambini', 'luogo', 0, { mind: true, terrain: 'ghiaia', modus: 'ionio', hush: 0.45, lumina: 'accese',
      levels: { m_bambini: 0.45, m_altalena: 0.2, m_uccelli: 0.2, m_campane: 0.12 }, set: { lumen: 0.4, nastro: 0.4, oblio: 0.4 }, libra: 0.78,
      pal: { bg: [13, 12, 10], accent: [240, 220, 180], second: [170, 160, 130] }, motif: { dream: 0.4, sun: 0.4, swing: 0.3 },
      ora: 'Un paese intero dove non c’è nemmeno un adulto. I bambini fanno il pane, guidano l’autobus, suonano le campane. Ti salutano per nome. Anche tu, qui, sei piccolo.',
      allora: 'Tra loro ci sono i tuoi nonni, da bambini. E i tuoi amici. E forse anche Giorgio.' }),
    N('neve_agosto', 'La neve d’agosto', 'luogo', 0, { mind: true, terrain: 'neve', modus: 'armonici', hush: 0.8, peace: 70, lumina: 'accese',
      levels: { m_cicale: 0.25, m_vento: 0.15, m_carezza: 0.2, m_campane: 0.06 }, set: { lumen: 0.45, aether: 0.7, chorus: 0.3 }, libra: 0.88,
      pal: { bg: [14, 13, 12], accent: [250, 246, 236], second: [220, 190, 150] }, motif: { dream: 0.5, snow: 1, sun: 0.4 },
      ora: 'Un pomeriggio d’agosto, le cicale, il caldo. E cade la neve: grossi fiocchi lenti che si sciolgono prima di toccare terra.',
      allora: 'Ti sembra di averlo visto davvero, da bambino, dalla finestra della nonna. Non è possibile. Eppure.' }),
    N('figlio_grande', 'Tuo figlio da grande', 'stato', 0, { mind: true, terrain: 'erba', modus: 'lidio', hush: 0.8, peace: 60, lumina: 'accese',
      levels: { m_voci: 0.1, m_uccelli: 0.25, m_carezza: 0.2, m_cuore: 0.12 }, set: { lumen: 0.45, velum: 0.55, chorus: 0.3 }, libra: 0.88,
      pal: { bg: [13, 12, 11], accent: [240, 226, 196], second: [180, 170, 150] }, motif: { dream: 0.5, meet: 0.5, sun: 0.4 },
      ora: 'Un uomo che ti somiglia ti viene incontro su un viale d’autunno. Ha il tuo modo di camminare. Ti sorride come quando era piccolo.',
      allora: 'Non è ancora successo. Forse succederà. È il ricordo di una cosa che deve ancora venire.' }),
    N('biblioteca_lettere', 'Le lettere che non ti hanno scritto', 'luogo', 0, { mind: true, terrain: 'legno', modus: 'eolio', hush: 0.85, lumina: 'candele',
      levels: { m_fruscio: 0.35, m_pendolo: 0.2, m_candele: 0.15, m_canto: 0.06 }, set: { lumen: 0.3, oblio: 0.45 }, libra: 0.88,
      pal: DREAM, motif: { dream: 0.5, candles: 0.4, motes: 0.6 },
      clues: ['Scaffali di buste chiuse, tutte indirizzate a te.', 'Una è di tua madre.', 'Una di tuo padre.', 'Una di Giorgio, una di Massimo.', 'Non le apri. Ti basta sapere che, da qualche parte, esistono.'],
      ora: 'Una stanza piena di lettere mai spedite, mai scritte, che nessuno ha avuto il tempo di scrivere.',
      allora: '' }),
    // ——————————————————————— IL NASCONDIGLIO (fuori dalla mappa: ci si arriva da ovunque)
    N('tana', 'Il nascondiglio', 'luogo', 0, { offmap: true, mind: true, terrain: 'nuvola', modus: 'pentatonico', hush: 1, peace: 12, lumina: 'candele', safe: true,
      levels: { m_carezza: 0.25, m_carillon: 0.15, m_respiro: 0.12, m_pioggia: 0.12 }, set: { lumen: 0.4, velum: 0.6, aether: 0.4, chorus: 0.25, nastro: 0, oblio: 0.2 }, libra: 0.98,
      pal: { bg: [14, 10, 8], accent: [255, 210, 160], second: [200, 140, 110] }, motif: { blanket: 1 },
      ora: 'Un posto tutto tuo, sotto le coperte: cuscini, plaid, una lucina calda. Fuori piove piano. Intorno, le tue cose: le macchinine, un libro, un orsetto, i pennarelli.',
      allora: 'Qui non entra nessuno, e nessuno ti chiede niente. Puoi restare quanto vuoi. Quando avrai voglia, la porta è lì.' })
  ];
  NEW.forEach(p => { if (!ATH.PLACE[p.id]) { ATH.PLACES.push(p); ATH.PLACE[p.id] = p; } });
  // Ora · Allora
  const AL = { casa_fretta: { m_voci: 0.25, m_stoviglie: 0.2, m_bambini: 0.15, m_pendolo: 0.3 }, casa_vandali: { m_voci: 0.2, m_bambini: 0.1 }, spartito: { m_bambini: 0.15, m_voci: 0.1 }, casa_mare_inverno: { m_bambini: 0.25, m_voci: 0.2, m_radio: 0.15 } };
  Object.keys(AL).forEach(id => { if (ATH.PLACE[id]) ATH.PLACE[id].alloraLevels = AL[id]; });
})(window.ATH);
