/* ATHANOR — I NUOVI QUARTIERI. Giugno, il sottoscala, i nonni giorno dopo
   giorno, Massimo, la cappella dei funerali sotto la pioggia, il nonno tra le
   stanze, il parco giochi fermo agli anni Settanta, la conca nel bosco. E poi
   il bosco profondo, il lago, le strade nella nebbia, il mare aperto e chi ci
   è rimasto sotto, la città vecchia, la città abbandonata, la palude, il
   cimitero monumentale, la montagna, la casa della signora sotto il velo, il
   manicomio, le stanze dell'orfanotrofio, lo studio cinematografico, la
   fabbrica chiusa, la sala giochi, la cabina, il rifugio, la metropolitana,
   il paese sommerso.
   Le strade tra i luoghi le disegna loca-layout.js.
   un luogo moderatamente sicuro */
window.ATH = window.ATH || {};

(function (ATH) {
  const NEW = [
    // ——————————————————————— LA TERRA · I NONNI
    { id: 'giorni_nonni', name: 'Giorno dopo giorno', kind: 'luogo', level: 0, terrain: 'legno', modus: 'lidio', hush: 0.45, lumina: 'accese',
      levels: { m_stoviglie: 0.3, m_pendolo: 0.3, m_radio: 0.18, m_voci: 0.2, m_uccelli: 0.15, m_camino: 0.15 }, set: { lumen: 0.35, velum: 0.4 }, libra: 0.65,
      pal: { bg: [16, 12, 9], accent: [240, 204, 150], second: [170, 120, 80] }, motif: { haze: 0.5, motes: 0.6, wallpaper: 0.25 },
      clues: ['La colazione col latte caldo, prima della scuola.', 'Il nonno che ti aspetta fuori dal cancello.', 'La nonna che ti cuce l’orlo dei pantaloni, di nuovo.', 'I compiti sul tavolo della cucina, con la radio accesa.', 'La sera, il telegiornale e il rumore dei piatti.', 'Ogni giorno. Non solo d’estate: ogni giorno.'],
      ora: 'La casa dei nonni in un giorno qualunque: l’orologio, la radio bassa, le stoviglie nel lavello, qualcuno che chiama il tuo nome dall’altra stanza.',
      allora: 'Non ti hanno tenuto solo d’estate. Ti hanno cresciuto loro, un giorno dopo l’altro, senza mai dirlo, come se fosse la cosa più naturale del mondo.' },
    { id: 'sottoscala', name: 'Il sottoscala', kind: 'luogo', level: 0, terrain: 'legno', modus: 'pentatonico', hush: 0.92, peace: 50, lumina: 'soffuse',
      levels: { m_passi: 0.2, m_pendolo: 0.15, m_fruscio: 0.2, m_cuore: 0.12, m_voci: 0.08 }, set: { lumen: 0.3, velum: 0.25, distantia: 0.55, oblio: 0.2 }, libra: 0.85, bpm: 0.35,
      pal: { bg: [12, 9, 7], accent: [240, 196, 140], second: [150, 100, 70] }, motif: { nook: 1, motes: 0.6 },
      ora: 'Il triangolo di buio sotto i gradini. Sopra la testa passano i piedi degli adulti, legno che scricchiola, voci che non ti cercano. Qui dentro nessuno ti trova.',
      allora: 'Ti nascondevi qui, da piccolo, con le ginocchia al petto. Era il tuo posto sicuro. Lo è ancora: basta chiudere gli occhi per tornarci.' },
    { id: 'nonno_malato', name: 'Il nonno tra le stanze', kind: 'stato', level: 0, terrain: 'legno', modus: 'eolio', hush: 0.75, lumina: 'soffuse',
      levels: { m_passi: 0.35, m_respiro: 0.3, m_pendolo: 0.3, m_scricchiolio: 0.25, m_tubature: 0.1 }, set: { lumen: 0.25, distantia: 0.4, oblio: 0.3 }, libra: 0.8, bpm: 0.3,
      pal: { bg: [11, 10, 9], accent: [214, 200, 178], second: [120, 108, 96] }, motif: { corridor: 0.7, motes: 0.5 },
      clues: ['Un passo. Poi la mano sul muro. Poi un altro passo.', 'Dalla camera alla cucina ci mette tanto.', 'Non vuole aiuto. Dice che ce la fa.', 'Tu lo guardi dalla porta e non sai cosa fare.', 'Lui ti vede, e prova a sorridere.'],
      ora: 'Il nonno, malato, si trascina da una stanza all’altra. Le pantofole strisciano sul pavimento, il fiato è corto, la mano cerca lo stipite.',
      allora: 'Era l’uomo più forte che conoscessi. Vederlo così ti ha insegnato una cosa che non sai ancora dire.' },
    // ——————————————————————— IL PAESE
    { id: 'parco_giochi', name: 'Il parco giochi', kind: 'luogo', level: 0, terrain: 'ghiaia', modus: 'lidio', hush: 0.35, lumina: 'soffuse',
      levels: { m_altalena: 0.55, m_vento: 0.35, m_bambini: 0.12, m_uccelli: 0.15, m_carillon: 0.12 }, set: { lumen: 0.3, nastro: 0.55, oblio: 0.45 }, libra: 0.6,
      pal: { bg: [14, 12, 10], accent: [226, 170, 110], second: [120, 150, 140] }, motif: { swing: 1, haze: 0.4, ruin: 0.25 },
      ora: 'Le giostre di ferro verniciato, scrostate. Il cavallino a molla, lo scivolo a razzo, la giostra a girello arrugginita. L’altalena cigola da sola.',
      allora: 'Sembra fermo al 1975: i colori di allora, sbiaditi da cinquant’anni di sole. È bellissimo, come tutte le cose che nessuno ha avuto il cuore di buttare via.' },
    // ——————————————————————— IL BOSCO
    { id: 'conca', name: 'La conca nel bosco', kind: 'luogo', level: 0, terrain: 'foglie', modus: 'insen', hush: 0.85, peace: 60, lumina: 'soffuse',
      levels: { m_vento: 0.3, m_uccelli: 0.2, m_fruscio: 0.3, m_respiro: 0.12, m_goccia: 0.1 }, set: { lumen: 0.35, velum: 0.35, aether: 0.5 }, libra: 0.88,
      pal: { bg: [7, 10, 8], accent: [190, 214, 170], second: [90, 120, 90] }, motif: { trees: 1, haze: 0.5, motes: 0.4 },
      ora: 'Il terreno scende in una piccola conca. Gli alberi si stringono intorno, vicini, come persone che non dicono niente. Ti fermi qui.',
      allora: 'Ci vieni a pensare. Il vento passa in alto, sulle cime; quaggiù non arriva. Arrivano solo i pensieri, uno alla volta.' },
    { id: 'bosco_profondo', name: 'Il bosco profondo', kind: 'luogo', level: 0, terrain: 'foglie', modus: 'hirajoshi', hush: 0.3, lumina: 'soffuse',
      levels: { m_vento: 0.4, m_civetta: 0.35, m_fruscio: 0.5, m_scricchiolio: 0.3, m_sussurri: 0.15, m_passi: 0.15 }, set: { lumen: 0.2, distantia: 0.65, mercurius: 0.5 }, libra: 0.55,
      pal: { bg: [4, 6, 5], accent: [140, 180, 150], second: [50, 70, 60] }, motif: { trees: 1, forest: 0.6 },
      ora: 'I tronchi sono tutti uguali. Il sentiero è finito da un pezzo e non sai quando. Qualcosa cammina con te, sempre un passo indietro.',
      allora: 'Da bambino ti dicevano di non entrarci. Adesso capisci: non perché ci fosse qualcuno, ma perché qui ci si dimentica da dove si è venuti.' },
    { id: 'lago', name: 'Il lago di notte', kind: 'luogo', level: 0, terrain: 'sabbia', modus: 'eolio', hush: 0.6, lumina: 'soffuse',
      levels: { m_rane: 0.4, m_grilli: 0.35, m_civetta: 0.2, m_goccia: 0.15, m_vento: 0.15, m_campane: 0.06 }, set: { lumen: 0.35, aether: 0.7, crypta: 0.7 }, libra: 0.75,
      pal: { bg: [5, 7, 11], accent: [190, 210, 236], second: [70, 90, 130] }, motif: { lake: 1, stars: 0.6, fireflies: 0.4 },
      ora: 'L’acqua nera ai piedi del bosco, ferma come vetro. Dentro c’è la luna, intera. Le rane, poi un silenzio improvviso, poi di nuovo le rane.',
      allora: 'Dicono che sotto ci sia un paese, sommerso quando hanno fatto la diga. Nelle notti senza vento si sentirebbero le campane.' },
    { id: 'palude', name: 'La palude', kind: 'luogo', level: 0, terrain: 'acqua', modus: 'hirajoshi', hush: 0.25, lumina: 'soffuse',
      levels: { m_rane: 0.6, m_bolle: 0.35, m_grilli: 0.3, m_ronzio: 0.25, m_goccia: 0.2, m_sussurri: 0.08 }, set: { lumen: 0.2, solutio: 0.35, putrefactio: 0.5, distantia: 0.5 }, libra: 0.5,
      pal: { bg: [7, 8, 5], accent: [176, 190, 120], second: [80, 90, 50] }, motif: { fog: 0.7, fireflies: 0.5, haze: 0.4 },
      ora: 'L’acqua bassa e scura tra i giunchi, le bolle che salgono dal fondo, il coro delle rane che non finisce mai. Ogni passo affonda un poco.',
      allora: 'Si diceva che i fuochi fatui fossero anime. Tu li guardavi dal finestrino dell’auto, e ci credevi.' },
    // ——————————————————————— LA CAMPAGNA
    { id: 'strade_nebbia', name: 'Le strade nella nebbia', kind: 'luogo', level: 0, terrain: 'ghiaia', modus: 'dorico', hush: 0.55, lumina: 'soffuse',
      levels: { m_motore: 0.45, m_cani: 0.2, m_grilli: 0.15, m_vento: 0.2, m_campane: 0.05 }, set: { lumen: 0.3, velum: 0.2, distantia: 0.75, crypta: 0.6 }, libra: 0.7,
      pal: { bg: [10, 11, 12], accent: [216, 220, 214], second: [120, 126, 130] }, motif: { fog: 1 },
      ora: 'La strada di campagna di notte, e la nebbia così fitta che i fari ci sbattono contro. Un cane abbaia da una cascina che non vedi. Due luci arrivano, ti passano accanto, spariscono.',
      allora: 'Tornavi a casa così, piano, con il finestrino appena abbassato per sentire. Le righe bianche, una alla volta, erano tutto il mondo.' },
    // ——————————————————————— IL MARE
    { id: 'mare_aperto', name: 'Il mare aperto', kind: 'luogo', level: 0, terrain: 'acqua', modus: 'eolio', hush: 0.3, lumina: 'soffuse',
      levels: { m_mare: 0.6, m_vento: 0.5, m_balena: 0.3, m_gabbiani: 0.05, m_scricchiolio: 0.2 }, set: { lumen: 0.3, crypta: 0.85, aether: 0.6, distantia: 0.5 }, libra: 0.55,
      pal: { bg: [4, 7, 10], accent: [150, 190, 214], second: [40, 70, 100] }, motif: { lake: 0.5, underwater: 0.25, stars: 0.4 },
      ora: 'Nessuna riva, da nessuna parte. Solo l’acqua che si alza e si abbassa, e sotto di te una profondità che non si può immaginare.',
      allora: 'Laggiù, molto più in basso della luce, c’è chi non è tornato. Navi, pescatori, gente che attraversava. Il mare non restituisce, ma non dimentica.' },
    // ——————————————————————— LA NOTTE
    { id: 'famiglia_spezzata', name: 'Una famiglia spezzata', kind: 'stato', level: 0, terrain: 'legno', modus: 'eolio', hush: 0.85, lumina: 'spente', candles: true,
      levels: { m_pianto: 0.35, m_pioggia: 0.3, m_pendolo: 0.2, m_respiro: 0.2, m_motore: 0.06 }, set: { lumen: 0.25, velum: 0.3, distantia: 0.5, oblio: 0.3 }, libra: 0.85,
      pal: { bg: [7, 7, 9], accent: [196, 200, 220], second: [90, 96, 120] }, motif: { tears: 0.6, ceiling: 0.6 },
      clues: ['Hai saputo della figlia del tuo amico.', 'Un incidente, una strada, una sera come le altre.', 'Ti sei messo a letto e non riuscivi a smettere.', 'Pensavi a loro: alla casa, alla sua stanza, al posto vuoto a tavola.', 'Ti sei sentito dentro quella famiglia. Come se fosse la tua.', 'Piangere per qualcuno che non conoscevi bene non è strano. È voler bene.'],
      ora: 'Al buio, nel letto, a occhi aperti. Fuori piove. Non riesci a smettere di piangere, e non è per te.',
      allora: 'Accendi un lumino per lei, se vuoi.' },
    { id: 'nessuno_parla', name: 'Nessuno che parla', kind: 'stato', level: 0, terrain: 'nuvola', modus: 'armonici', hush: 1, peace: 25, lumina: 'soffuse',
      levels: { m_vento: 0.08, m_carezza: 0.12 }, set: { lumen: 0.3, velum: 0.5, aether: 0.5, nastro: 0, oblio: 0.2 }, libra: 0.97,
      pal: { bg: [12, 12, 13], accent: [220, 220, 226], second: [150, 150, 160] }, motif: { haze: 0.6, void: 0.3 },
      whisperWords: [],
      ora: 'Nessuno che parla. Nessuna domanda, nessuna risposta, nessuna voce. Solo l’aria della stanza.',
      allora: 'A volte non vuoi altro. Non è tristezza: è riposo. Qui puoi restare quanto vuoi, e nessuno ti chiederà niente.' },
    { id: 'giugno', name: 'Giugno', kind: 'stato', level: 0, terrain: 'erba', modus: 'lidio', hush: 0.5, lumina: 'luogo',
      levels: { m_cicale: 0.35, m_grilli: 0.3, m_vagito: 0.12, m_pianto: 0.12, m_campane: 0.12, m_vento: 0.2, m_cuore: 0.15 }, set: { lumen: 0.4, velum: 0.45, chorus: 0.2 }, libra: 0.7,
      pal: { bg: [14, 12, 10], accent: [250, 214, 150], second: [120, 140, 190] }, motif: { fireflies: 1, sun: 0.35, haze: 0.4 },
      clues: ['A giugno hai perso tutto.', 'A giugno le giornate non finiscono mai.', 'A giugno qualcuno se n’è andato.', 'A giugno è nato tuo figlio.', 'E da quel momento è cambiato tutto, di nuovo, al contrario.', 'Giugno è un mese strano: toglie e dà con la stessa mano.'],
      ora: 'Le sere lunghe, le lucciole nei campi, il caldo che arriva di colpo. Il mese in cui tutto finisce, e il mese in cui tutto comincia.',
      allora: '' },
    // ——————————————————————— LA CASA DELLA SIGNORA
    { id: 'casa_velo', name: 'La signora sotto il velo', kind: 'luogo', level: 0, terrain: 'legno', modus: 'eolio', hush: 0.9, lumina: 'candele', candles: true,
      levels: { m_pendolo: 0.0, m_candele: 0.4, m_fruscio: 0.15, m_sussurri: 0.12, m_passi: 0.1 }, set: { lumen: 0.25, distantia: 0.5, oblio: 0.4 }, libra: 0.85,
      pal: { bg: [9, 8, 8], accent: [230, 214, 196], second: [120, 104, 96] }, motif: { veil: 1, candles: 0.7 },
      clues: ['Hanno fermato l’orologio.', 'Hanno coperto lo specchio con un panno nero.', 'Le persiane sono accostate da tre giorni.', 'Qualcuno, di là, dice il rosario sottovoce.', 'Sotto il velo bianco si indovina appena il profilo.'],
      ora: 'Una casa vecchia, la camera buona. Sul letto la signora, distesa, con un velo bianco sopra il corpo. Due candele, le sedie in fila lungo il muro.',
      allora: 'Si vegliavano così, i morti, una volta: in casa, tra le loro cose. Si entrava piano, si stava un po’, si usciva senza far rumore.' },
    // ——————————————————————— IL MANICOMIO
    { id: 'manicomio', name: 'Il manicomio', kind: 'luogo', level: 0, terrain: 'pietra', modus: 'hirajoshi', hush: 0.2, lumina: 'soffuse',
      levels: { m_voci: 0.3, m_sussurri: 0.35, m_passi: 0.35, m_ronzio: 0.35, m_tubature: 0.2, m_pianto: 0.12, m_canto: 0.08 }, set: { lumen: 0.15, nastro: 0.4, distantia: 0.4, tempestas: 0.35 }, libra: 0.45,
      pal: { bg: [9, 10, 10], accent: [200, 214, 206], second: [100, 116, 110] }, motif: { corridor: 1, whispers: 0.5 },
      clues: ['Qualcuno canta sempre la stessa strofa.', 'Qualcuno conta i passi, avanti e indietro.', 'Qualcuno chiede a tutti se è arrivata la lettera.', 'Molti erano qui solo perché davano fastidio.', 'Nessuno li veniva a trovare.'],
      ora: 'Corridoi verdi fino a metà parete, porte con lo spioncino, il neon che ronza. Da ogni stanza una voce diversa, nessuna che risponde a un’altra.',
      allora: 'Ci chiudevano chi non sapevano dove mettere: i matti, i tristi, i diversi, i soli. Erano persone. Avevano un nome, prima del numero.' },
    { id: 'manicomio_abb', name: 'Il manicomio abbandonato', kind: 'luogo', level: 0, terrain: 'pietra', modus: 'insen', hush: 0.6, lumina: 'torcia',
      levels: { m_vento: 0.4, m_goccia: 0.3, m_scricchiolio: 0.3, m_sussurri: 0.2, m_uccelli: 0.06 }, set: { lumen: 0.15, distantia: 0.7, crypta: 0.8, oblio: 0.5 }, libra: 0.65,
      pal: { bg: [8, 9, 9], accent: [190, 200, 196], second: [90, 100, 96] }, motif: { corridor: 0.8, ruin: 0.8 },
      ora: 'I letti di ferro sono ancora lì, senza materasso. Sui muri scrostati qualcuno ha scritto il proprio nome, tante volte. Entra la pioggia dal tetto.',
      allora: 'Lo hanno chiuso. Le persone sono andate via, o sono rimaste qui per sempre. Restano i nomi sul muro, e il vento nei corridoi.' },
    // ——————————————————————— L'ORFANOTROFIO: LE STANZE
    { id: 'cortile', name: 'Il cortile', kind: 'luogo', level: 0, terrain: 'ghiaia', modus: 'dorico', hush: 0.35, lumina: 'soffuse',
      levels: { m_bambini: 0.35, m_vento: 0.3, m_campane: 0.15, m_uccelli: 0.15, m_passi: 0.15 }, set: { lumen: 0.3, nastro: 0.4, oblio: 0.4 }, libra: 0.6,
      pal: { bg: [12, 11, 10], accent: [220, 206, 180], second: [120, 110, 100] }, motif: { haze: 0.4, ruin: 0.3 },
      ora: 'Un cortile di ghiaia tra quattro muri alti. Un pallone sgonfio contro la rete, un albero solo. La campanella dell’intervallo suona per nessuno.',
      allora: 'Si giocava in silenzio, qui. Le suore guardavano dalla finestra. Ognuno sapeva chi aveva qualcuno fuori, e chi no.' },
    { id: 'refettorio', name: 'Il refettorio', kind: 'luogo', level: 0, terrain: 'pietra', modus: 'eolio', hush: 0.55, lumina: 'soffuse',
      levels: { m_stoviglie: 0.45, m_voci: 0.15, m_passi: 0.2, m_ronzio: 0.15, m_campane: 0.06 }, set: { lumen: 0.2, distantia: 0.5, crypta: 0.6 }, libra: 0.7,
      pal: { bg: [11, 10, 9], accent: [214, 200, 176], second: [110, 100, 90] }, motif: { corridor: 0.4, motes: 0.5 },
      ora: 'Tavoli lunghi, panche di legno, scodelle di latta in fila. Il cucchiaio che batte sul fondo. Una preghiera prima, in coro, a voce bassa.',
      allora: 'Si mangiava in fretta e senza parlare. Chi finiva per primo guardava il piatto degli altri.' },
    { id: 'aula', name: 'L’aula', kind: 'luogo', level: 0, terrain: 'legno', modus: 'dorico', hush: 0.7, lumina: 'soffuse',
      levels: { m_pendolo: 0.35, m_fruscio: 0.2, m_bambini: 0.08, m_scricchiolio: 0.15 }, set: { lumen: 0.25, nastro: 0.5, oblio: 0.5 }, libra: 0.75,
      pal: { bg: [10, 11, 10], accent: [200, 214, 196], second: [90, 110, 96] }, motif: { motes: 0.7, windows: 0.3 },
      ora: 'I banchi di legno col buco per il calamaio. Sulla lavagna, mezza cancellata, una frase scritta con una bella calligrafia. L’orologio sopra la porta va avanti a scatti.',
      allora: 'Qualcuno, su quel banco, ha inciso un nome col compasso. Era l’unico modo per restare da qualche parte.' },
    { id: 'lavatoio', name: 'Il lavatoio', kind: 'luogo', level: 0, terrain: 'acqua', modus: 'insen', hush: 0.6, lumina: 'soffuse',
      levels: { m_goccia: 0.5, m_tubature: 0.35, m_bolle: 0.12, m_canto: 0.08 }, set: { lumen: 0.2, crypta: 0.85, distantia: 0.5 }, libra: 0.7,
      pal: { bg: [8, 10, 11], accent: [190, 210, 220], second: [80, 100, 110] }, motif: { glass: 0.4, haze: 0.5 },
      ora: 'Le vasche di pietra in fila, i rubinetti di ottone, l’acqua che gocciola da cinquant’anni. Un’eco lunga, che restituisce ogni goccia.',
      allora: 'L’acqua era sempre fredda. Ci si lavava in fretta, la mattina, tutti insieme, senza guardarsi.' },
    { id: 'infermeria', name: 'L’infermeria', kind: 'luogo', level: 0, terrain: 'pietra', modus: 'eolio', hush: 0.75, lumina: 'soffuse',
      levels: { m_respiro: 0.3, m_pendolo: 0.25, m_ronzio: 0.2, m_pianto: 0.08, m_carillon: 0.06 }, set: { lumen: 0.25, velum: 0.3, oblio: 0.4 }, libra: 0.8,
      pal: { bg: [11, 11, 11], accent: [226, 226, 220], second: [130, 130, 126] }, motif: { fever: 0.4, motes: 0.4 },
      ora: 'Due lettini con le lenzuola bianche, un armadietto di vetro con le bottigliette scure. Odore di disinfettante e di brodo.',
      allora: 'Quando avevi la febbre ti portavano qui. Era l’unico posto dove qualcuno ti metteva una mano sulla fronte.' },
    { id: 'parlatorio', name: 'Il parlatorio', kind: 'luogo', level: 0, terrain: 'legno', modus: 'eolio', hush: 0.8, lumina: 'soffuse',
      levels: { m_pendolo: 0.4, m_passi: 0.15, m_campane: 0.1, m_vento: 0.1 }, set: { lumen: 0.25, distantia: 0.5, oblio: 0.35 }, libra: 0.8,
      pal: { bg: [11, 10, 9], accent: [214, 196, 170], second: [110, 96, 84] }, motif: { windows: 0.4, motes: 0.5 },
      clues: ['La domenica, dalle tre alle cinque, le visite.', 'Si aspettava seduti sulle sedie lungo il muro.', 'Ogni volta che si apriva la porta, tutti alzavano la testa.', 'Per qualcuno non veniva mai nessuno.', 'Alle cinque si tornava su, senza dire niente.'],
      ora: 'Una stanza con le sedie lungo il muro e una grata. L’orologio a pendolo. La porta da cui, la domenica, entravano i parenti.',
      allora: '' },
    // ——————————————————————— LA CHIESA E IL CIMITERO
    { id: 'cappella_funebre', name: 'La cappella dei funerali', kind: 'luogo', level: 0, terrain: 'pietra', modus: 'eolio', hush: 0.25, lumina: 'candele',
      levels: { m_vetrate: 0.65, m_pioggia: 0.55, m_vento: 0.45, m_organo: 0.15, m_candele: 0.25, m_tuono: 0.12 }, set: { lumen: 0.2, crypta: 0.9, distantia: 0.4 }, libra: 0.55,
      pal: { bg: [7, 7, 9], accent: [214, 160, 120], second: [80, 110, 150] }, motif: { vetrate: 1, candles: 0.5, rainfall: 0.5 },
      ora: 'La cappella in fondo al cimitero, dove si dice l’ultima messa. Fuori piove forte: il vento spinge contro le vetrate colorate e le fa tremare nei piombi, e il rumore riempie tutto.',
      allora: 'Ai funerali stavi in fondo, vicino alla porta. Ricordi più il fracasso dei vetri nella pioggia che le parole del prete.' },
    { id: 'massimo', name: 'Da Massimo', kind: 'luogo', level: 0, terrain: 'ghiaia', modus: 'ionio', hush: 0.55, lumina: 'candele', candles: true,
      levels: { m_vento: 0.3, m_uccelli: 0.2, m_passi: 0.12, m_arcade: 0.12, m_campane: 0.06 }, set: { lumen: 0.35, velum: 0.35, distantia: 0.45 }, libra: 0.72,
      pal: { bg: [10, 10, 12], accent: [214, 220, 240], second: [120, 160, 220] }, motif: { tombs: 0.6, arcade: 0.3, candles: 0.4 },
      clues: ['Ciao Massimo. Sono io.', 'Ti racconto un po’ di cose.', 'È uscito quel gioco che aspettavamo. Ci ho giocato anche per te.', 'Ne escono di nuovi, sempre. Te li racconto tutti, uno per uno.', 'Ti dico com’è andata la settimana, il lavoro, la casa.', 'Non rispondi, ma va bene così. Torno presto.'],
      ora: 'Ti siedi sul bordo di marmo, davanti alla sua foto. Togli una foglia secca, sistemi i fiori. Poi cominci a parlare, piano, come si fa tra amici.',
      allora: 'Vieni a trovarlo per raccontargli le cose. Anche le più piccole, anche i videogiochi che escono: soprattutto quelli.' },
    { id: 'monumentale', name: 'Il cimitero monumentale', kind: 'luogo', level: 0, terrain: 'ghiaia', modus: 'eolio', hush: 0.6, lumina: 'candele', candles: true,
      levels: { m_vento: 0.45, m_campane: 0.15, m_uccelli: 0.15, m_passi: 0.2, m_candele: 0.2, m_canto: 0.06 }, set: { lumen: 0.3, crypta: 0.9, distantia: 0.6, aether: 0.5 }, libra: 0.75,
      pal: { bg: [9, 9, 10], accent: [220, 214, 200], second: [110, 112, 116] }, motif: { tombs: 1, rose: 0.15, haze: 0.3 },
      ora: 'Viali di cipressi, cappelle di famiglia con le porte di ferro battuto, angeli di marmo con le ali consumate dalla pioggia. Migliaia di nomi.',
      allora: 'Gente importante, una volta. Adesso ha la stessa pace di tutti gli altri, e lo stesso muschio sulle lettere.' },
    // ——————————————————————— LA CITTÀ
    { id: 'citta_vecchia', name: 'La città vecchia', kind: 'luogo', level: 0, terrain: 'pietra', modus: 'dorico', hush: 0.3, lumina: 'soffuse',
      levels: { m_pioggia: 0.65, m_goccia: 0.35, m_passi: 0.25, m_campane: 0.15, m_tubature: 0.15, m_voci: 0.08 }, set: { lumen: 0.3, crypta: 0.7, distantia: 0.4 }, libra: 0.6,
      pal: { bg: [8, 9, 11], accent: [214, 190, 150], second: [90, 110, 140] }, motif: { rainfall: 1, windows: 0.6 },
      ora: 'Vicoli stretti, lastricati lucidi, portici. Qui piove sempre: le grondaie traboccano, le finestre sono accese di giallo, un ombrello solo attraversa la piazza.',
      allora: 'La pioggia qui non è maltempo: è il suono della città. Senza, sembrerebbe morta.' },
    { id: 'sala_giochi', name: 'La sala giochi', kind: 'luogo', level: 0, terrain: 'pietra', modus: 'ionio', hush: 0.2, lumina: 'soffuse',
      levels: { m_arcade: 0.7, m_ronzio: 0.3, m_voci: 0.12, m_bambini: 0.08 }, set: { lumen: 0.25, nastro: 0.35, oblio: 0.3 }, libra: 0.4,
      pal: { bg: [6, 5, 10], accent: [120, 220, 255], second: [240, 90, 200] }, motif: { arcade: 1 },
      ora: 'Il buio, e i cabinati accesi in fila, ognuno con la sua musica. Il gettone che cade, i tasti consumati, la scritta che lampeggia: INSERT COIN.',
      allora: 'Ci passavi i pomeriggi, con le monete contate. C’era sempre qualcuno più bravo, dietro di te, a guardare.' },
    { id: 'cabina', name: 'La cabina telefonica', kind: 'luogo', level: 0, terrain: 'pietra', modus: 'eolio', hush: 0.6, lumina: 'soffuse',
      levels: { m_telefono: 0.4, m_pioggia: 0.35, m_motore: 0.15, m_radio: 0.12 }, set: { lumen: 0.25, nastro: 0.5, distantia: 0.5 }, libra: 0.7,
      pal: { bg: [8, 9, 10], accent: [230, 200, 120], second: [100, 110, 120] }, motif: { rainfall: 0.6, lights: 0.4 },
      clues: ['Hai ancora un gettone.', 'Componi un numero che sai a memoria.', 'Squilla.', 'Squilla ancora.', 'Nessuno risponde. Quel numero non esiste più da tanto.'],
      ora: 'Una cabina sotto la pioggia, la luce al neon che sfarfalla, i vetri coperti di scritte. La cornetta è ancora attaccata al filo.',
      allora: '' },
    // ——————————————————————— LE ROVINE
    { id: 'citta_abbandonata', name: 'La città abbandonata', kind: 'luogo', level: 0, terrain: 'pietra', modus: 'insen', hush: 0.45, lumina: 'soffuse',
      levels: { m_vento: 0.55, m_scricchiolio: 0.2, m_goccia: 0.15, m_cani: 0.12, m_uccelli: 0.08 }, set: { lumen: 0.2, crypta: 0.85, distantia: 0.75 }, libra: 0.6,
      pal: { bg: [8, 8, 8], accent: [200, 196, 186], second: [100, 98, 94] }, motif: { city: 0.8, ruin: 1 },
      ora: 'Le strade vuote, le serrande abbassate, l’erba che spacca l’asfalto. Un semaforo cambia colore per nessuno. Il vento sbatte un’imposta, sempre la stessa.',
      allora: 'Se ne sono andati tutti, un po’ alla volta. L’ultimo ha chiuso la porta a chiave, come se dovesse tornare.' },
    { id: 'fabbrica', name: 'La fabbrica chiusa', kind: 'luogo', level: 0, terrain: 'pietra', modus: 'dorico', hush: 0.5, lumina: 'soffuse', candles: true,
      levels: { m_vento: 0.4, m_goccia: 0.25, m_macchine: 0.0, m_scricchiolio: 0.25, m_ronzio: 0.12 }, set: { lumen: 0.2, crypta: 0.9, distantia: 0.6 }, libra: 0.65,
      pal: { bg: [9, 8, 7], accent: [220, 170, 110], second: [110, 90, 70] }, motif: { machine: 1, ruin: 0.5 },
      ora: 'I capannoni enormi e muti. Al cancello, legato col fil di ferro, un mazzo di fiori secchi e una fotografia scolorita sotto la plastica.',
      allora: 'Era piena di rumore: la pressa, i carrelli, la sirena dei turni. Poi un giorno un operaio non è tornato a casa, e dopo di lui non è più tornato nessuno.' },
    { id: 'reparto', name: 'Il reparto fermo', kind: 'luogo', level: 0, terrain: 'pietra', modus: 'eolio', hush: 0.85, lumina: 'torcia',
      levels: { m_goccia: 0.25, m_vento: 0.2, m_ronzio: 0.15, m_macchine: 0.0 }, set: { lumen: 0.2, distantia: 0.6, oblio: 0.4 }, libra: 0.8,
      pal: { bg: [8, 8, 8], accent: [210, 200, 180], second: [100, 96, 90] }, motif: { machine: 0.8, motes: 0.6 },
      ora: 'Le macchine coperte di polvere, ferme a metà di un gesto. Negli spogliatoi, un armadietto ha ancora il nome scritto col pennarello, e dentro una tuta appesa.',
      allora: 'Nessuno ha avuto il coraggio di svuotarlo. Il reparto è rimasto così, come quel giorno: in silenzio, per rispetto.' },
    { id: 'studio_cine', name: 'Lo studio cinematografico', kind: 'luogo', level: 0, terrain: 'legno', modus: 'lidio', hush: 0.45, lumina: 'soffuse',
      levels: { m_proiettore: 0.4, m_vento: 0.3, m_grammofono: 0.15, m_scricchiolio: 0.25, m_voci: 0.08 }, set: { lumen: 0.3, nastro: 0.6, oblio: 0.5 }, libra: 0.6,
      pal: { bg: [10, 9, 8], accent: [236, 214, 170], second: [130, 110, 90] }, motif: { film: 0.8, beam: 0.4 },
      ora: 'I teatri di posa vuoti, alti come chiese. Riflettori spenti appesi alle travi, una sedia di tela con un nome sopra, una claquette per terra.',
      allora: 'Qui si fabbricavano i sogni degli altri. Quando hanno chiuso, i sogni sono rimasti: appoggiati ai muri, a pezzi.' },
    { id: 'set_film', name: 'Il set abbandonato', kind: 'luogo', level: 0, terrain: 'sabbia', modus: 'hirajoshi', hush: 0.5, lumina: 'soffuse',
      levels: { m_vento: 0.55, m_scricchiolio: 0.3, m_proiettore: 0.12, m_cani: 0.06 }, set: { lumen: 0.25, distantia: 0.7, crypta: 0.6 }, libra: 0.65,
      pal: { bg: [11, 9, 7], accent: [226, 190, 140], second: [120, 90, 70] }, motif: { film: 0.5, ruin: 0.8, city: 0.4 },
      ora: 'Una strada del vecchio West fatta di facciate: dietro le porte del saloon non c’è niente, solo travi e sacchi di sabbia. Un castello di cartapesta crolla piano nel vento.',
      allora: 'Tutto finto, eppure ci hai creduto, al cinema, da bambino. Forse è questo il trucco: anche le cose finte, se ci credi, ti restano dentro.' },
    { id: 'sala_proiezione', name: 'La sala di proiezione', kind: 'luogo', level: 0, terrain: 'legno', modus: 'pentatonico', hush: 0.7, lumina: 'soffuse',
      levels: { m_proiettore: 0.7, m_fruscio: 0.3, m_piano: 0.15, m_grammofono: 0.1 }, set: { lumen: 0.3, nastro: 0.7, oblio: 0.6, velum: 0.3 }, libra: 0.75,
      pal: { bg: [6, 6, 6], accent: [240, 232, 210], second: [120, 116, 110] }, motif: { film: 1, beam: 0.8 },
      ora: 'Il fascio di luce attraversa il buio pieno di polvere. Sullo schermo, graffiate, scorrono immagini di gente che ride, che balla, che saluta. Nessuno in sala.',
      allora: 'Sono tutti morti, quelli che salutano. Ma sullo schermo salutano ancora, ogni volta che qualcuno accende la macchina.' },
    // ——————————————————————— LE TORRI · L'OSPEDALE · LA MONTAGNA
    { id: 'figlio', name: 'Tuo figlio', kind: 'stato', level: 1, terrain: 'legno', modus: 'lidio', hush: 0.7, peace: 70, lumina: 'soffuse',
      levels: { m_vagito: 0.25, m_cuore: 0.3, m_carillon: 0.25, m_respiro: 0.2, m_carezza: 0.2 }, set: { lumen: 0.45, velum: 0.55, chorus: 0.3, aether: 0.4 }, libra: 0.85, bpm: 0.45,
      pal: { bg: [14, 12, 12], accent: [255, 220, 190], second: [180, 190, 230] }, motif: { cradle: 1, purify: 0.2 },
      clues: ['È nato a giugno.', 'Così piccolo che ti stava in due mani.', 'Ha stretto il tuo dito, e non l’ha più lasciato.', 'Hai capito che adesso il centro del mondo era lui.', 'Tutto quello che avevi perso, non l’hai ritrovato: è arrivato qualcosa di nuovo.'],
      ora: 'Il primo vagito, poi il silenzio stupito, poi il suo respiro contro il tuo petto. Una cosa così piccola, e il mondo intero si sposta.',
      allora: 'Ti ha rivoluzionato tutto. Le notti, le priorità, la paura, la gioia. Sei diventato il padre che a te è mancato.' },
    { id: 'sentiero', name: 'Il sentiero di montagna', kind: 'luogo', level: 1, terrain: 'ghiaia', modus: 'dorico', hush: 0.4, lumina: 'accese',
      levels: { m_vento: 0.5, m_uccelli: 0.25, m_campane: 0.12, m_passi: 0.3, m_goccia: 0.1 }, set: { lumen: 0.35, aether: 0.6, crypta: 0.7 }, libra: 0.65,
      pal: { bg: [9, 11, 13], accent: [210, 226, 236], second: [100, 130, 150] }, motif: { mountain: 1, haze: 0.4 },
      ora: 'Il sentiero sale tra i larici, poi tra i sassi. Lontano, i campanacci di una mandria. L’aria si fa fina e fredda.',
      allora: 'In montagna si parla poco. Si cammina, si guarda in giro, si respira. Il resto lo fa la salita.' },
    { id: 'baita', name: 'La baita', kind: 'luogo', level: 1, terrain: 'legno', modus: 'eolio', hush: 0.9, lumina: 'candele', candles: true,
      levels: { m_vento: 0.45, m_scricchiolio: 0.25, m_camino: 0.0, m_goccia: 0.1, m_pendolo: 0.12 }, set: { lumen: 0.25, distantia: 0.6, oblio: 0.4 }, libra: 0.85,
      pal: { bg: [9, 9, 10], accent: [214, 206, 196], second: [100, 104, 112] }, motif: { mountain: 0.6, motes: 0.5, candles: 0.4 },
      ora: 'Una baita di legno scuro, sola sotto il bosco. Il camino è freddo, la legna ancora impilata sotto la tettoia. Dentro tutto è in ordine, come se qualcuno stesse per tornare.',
      allora: 'Qui un uomo, da solo, ha smesso di vivere. Nessuno sa che cosa avesse nel cuore, e non sta a noi saperlo. Si può solo restare un momento in silenzio, e accendere un lumino.' },
    // ——————————————————————— I TETTI
    { id: 'vetta', name: 'La vetta', kind: 'luogo', level: 2, terrain: 'neve', modus: 'armonici', hush: 0.6, peace: 80, lumina: 'accese',
      levels: { m_vento: 0.55, m_campane: 0.06 }, set: { lumen: 0.45, aether: 0.85, chorus: 0.3, crypta: 0.9 }, libra: 0.85,
      pal: { bg: [10, 12, 15], accent: [236, 240, 250], second: [140, 170, 210] }, motif: { mountain: 0.8, snow: 0.4, sun: 0.2 },
      ora: 'In cima non c’è niente: una croce di ferro, il vento, e sotto le nuvole tutto il mondo che hai attraversato, piccolissimo.',
      allora: 'Da quassù non si vede nessuna strada. Si vede solo che tutto è collegato.' },
    { id: 'osservatorio', name: 'L’osservatorio', kind: 'luogo', level: 2, terrain: 'pietra', modus: 'armonici', hush: 0.7, lumina: 'soffuse',
      levels: { m_ronzio: 0.15, m_vento: 0.3, m_radio: 0.15, m_carezza: 0.12 }, set: { lumen: 0.35, aether: 0.8, chorus: 0.25 }, libra: 0.85,
      pal: { bg: [4, 5, 10], accent: [190, 200, 255], second: [90, 80, 160] }, motif: { stars: 1, nebula: 0.5 },
      ora: 'La cupola si apre con un rumore lungo di ingranaggi. Il telescopio ruota piano. Nell’oculare, una luce partita prima che nascesse chiunque tu conosca.',
      allora: 'Guardare le stelle è guardare il passato. Anche qui sotto, in fondo, è sempre così.' },
    // ——————————————————————— IL SOTTOSUOLO
    { id: 'rifugio', name: 'Il rifugio antiaereo', kind: 'luogo', level: -1, terrain: 'pietra', modus: 'insen', hush: 0.6, lumina: 'torcia',
      levels: { m_goccia: 0.35, m_ronzio: 0.25, m_respiro: 0.2, m_cuore: 0.15, m_sussurri: 0.12, m_tuono: 0.08 }, set: { lumen: 0.15, crypta: 0.85, distantia: 0.5 }, libra: 0.7, bpm: 0.55,
      pal: { bg: [7, 7, 6], accent: [200, 190, 160], second: [100, 90, 70] }, motif: { corridor: 0.6, ceiling: 0.4 },
      ora: 'Le panche lungo i muri di cemento, le frecce dipinte, una lampadina che pende dal soffitto. Lontanissimo, come un tuono, qualcosa cade.',
      allora: 'I nonni ci erano scesi davvero, da bambini, con la sirena che suonava. Te lo raccontavano a voce bassa, e poi cambiavano discorso.' },
    { id: 'metro', name: 'La metropolitana chiusa', kind: 'luogo', level: -1, terrain: 'pietra', modus: 'hirajoshi', hush: 0.35, lumina: 'spente',
      levels: { m_treno: 0.25, m_ronzio: 0.35, m_goccia: 0.3, m_vento: 0.3, m_passi: 0.12 }, set: { lumen: 0.15, crypta: 0.95, distantia: 0.6 }, libra: 0.55,
      pal: { bg: [6, 7, 8], accent: [180, 200, 210], second: [80, 100, 110] }, motif: { train: 0.6, corridor: 0.5 },
      ora: 'Una stazione murata decenni fa. Le piastrelle bianche, il nome della fermata a mosaico, i binari arrugginiti che si perdono nel buio. Ogni tanto passa un vento caldo, come un treno che non arriva.',
      allora: 'Dicono che ci passino ancora, i treni di una volta, di notte, senza passeggeri.' },
    // ——————————————————————— L'ABISSO
    { id: 'affondati', name: 'Quelli laggiù', kind: 'luogo', level: -2, terrain: 'acqua', modus: 'armonici', hush: 0.75, lumina: 'soffuse', candles: true,
      levels: { m_balena: 0.45, m_bolle: 0.25, m_canto: 0.12, m_cuore: 0.08 }, set: { lumen: 0.3, aether: 0.7, distantia: 0.8, crypta: 0.95, oblio: 0.5 }, libra: 0.85,
      pal: { bg: [2, 5, 8], accent: [120, 170, 200], second: [30, 60, 90] }, motif: { deep: 1, underwater: 0.5 },
      ora: 'Più giù della luce. Le navi coricate sul fondo, coperte di sabbia. Intorno, ferme nell’acqua scura, forme pallide che sembrano dormire.',
      allora: 'Erano marinai, pescatori, gente partita per un posto migliore. Nessuno ha messo un fiore sulla loro tomba, perché la loro tomba è tutto questo. Accendi un lumino per loro.' },
    { id: 'paese_sommerso', name: 'Il paese sommerso', kind: 'luogo', level: -2, terrain: 'acqua', modus: 'pentatonico', hush: 0.8, peace: 90, lumina: 'spente',
      levels: { m_campane: 0.3, m_bolle: 0.2, m_balena: 0.15, m_canto: 0.1 }, set: { lumen: 0.3, aether: 0.75, distantia: 0.8, oblio: 0.5 }, libra: 0.85,
      pal: { bg: [4, 8, 10], accent: [170, 210, 214], second: [60, 100, 110] }, motif: { underwater: 1, city: 0.3 },
      ora: 'Sotto il lago, il campanile è ancora in piedi. Le case con le finestre aperte, la piazza, la fontana. I pesci passano dentro le porte.',
      allora: 'Lo hanno lasciato affondare per fare la diga. La gente è andata a vivere altrove. Le campane, dicono, sono rimaste, e certe notti suonano da sole.' }
  ];
  NEW.forEach(p => { p.exits = p.exits || []; if (!p.motif) p.motif = {}; ATH.PLACES.push(p); ATH.PLACE[p.id] = p; });

  // i nonni non solo d'estate
  const est = ATH.PLACE.estate;
  if (est) { est.name = 'Le estati dai nonni'; est.allora = 'Il pomeriggio non finiva mai. Ma non c’erano solo le estati: c’erano anche tutti gli altri giorni, uno dopo l’altro.'; }
  // il bosco, la notte: anche la civetta
  if (ATH.PLACE.bosco) ATH.PLACE.bosco.levels.m_civetta = 0.2;
  if (ATH.PLACE.mare) ATH.PLACE.mare.levels.m_balena = 0.0;
  if (ATH.PLACE.funerale) ATH.PLACE.funerale.levels.m_vetrate = 0.2;
  if (ATH.PLACE.chiesa) ATH.PLACE.chiesa.levels.m_vetrate = 0.15;
  if (ATH.PLACE.pioggia) ATH.PLACE.pioggia.motif.rainfall = 0.5;
  if (ATH.PLACE.periferia) ATH.PLACE.periferia.levels.m_motore = 0.25;
  if (ATH.PLACE.campagna) ATH.PLACE.campagna.levels.m_motore = 0.1;
  if (ATH.PLACE.cimitero) ATH.PLACE.cimitero.levels.m_vetrate = 0.06;
})(window.ATH);

// Ora · Allora: i suoni di quando questi luoghi erano vivi
(function (ATH) {
  const AL = {
    fabbrica: { m_macchine: 0.65, m_voci: 0.2, m_passi: 0.2 }, reparto: { m_macchine: 0.5, m_voci: 0.12 },
    citta_abbandonata: { m_voci: 0.3, m_passi: 0.35, m_campane: 0.2, m_motore: 0.25, m_bambini: 0.15 },
    manicomio_abb: { m_voci: 0.3, m_sussurri: 0.25, m_passi: 0.25 }, parco_giochi: { m_bambini: 0.55, m_carillon: 0.15 },
    cortile: { m_bambini: 0.35 }, refettorio: { m_voci: 0.3, m_stoviglie: 0.2 }, aula: { m_bambini: 0.25, m_voci: 0.15 },
    studio_cine: { m_voci: 0.3, m_proiettore: 0.2, m_grammofono: 0.15 }, set_film: { m_voci: 0.25, m_cani: 0.1 },
    sala_proiezione: { m_voci: 0.15, m_piano: 0.2 }, sala_giochi: { m_bambini: 0.25, m_voci: 0.2 },
    casa_velo: { m_pendolo: 0.35, m_voci: 0.1 }, giorni_nonni: { m_voci: 0.2, m_bambini: 0.1 }, metro: { m_treno: 0.4, m_voci: 0.2 },
    paese_sommerso: { m_campane: 0.25 }, nonno_malato: { m_voci: 0.12 }, casa_vuota: { m_voci: 0.25, m_stoviglie: 0.2 }
  };
  Object.keys(AL).forEach(id => { if (ATH.PLACE[id]) ATH.PLACE[id].alloraLevels = AL[id]; });
})(window.ATH);
